from h import S, W, R, C, MENTOR_GENERIC

P1 = {}

P1["backend_development"] = C(
    "Backend dasturchi", "software", "Dasturlash",
    "Backend — ko'rinmaydigan qism: ma'lumot qayerda saqlanadi, qanday qoida bilan ishlaydi, server so'rovga qanday javob beradi. Mantiq va tizim qurishni yoqtiradigan odam uchun.",
    ["Junior Backend vakansiyalariga ariza berish", "Portfolio: 2–3 ta ishlaydigan API loyiha", "Ochiq loyihalarga kichik hissa qo'shish"],
    "Middle Backend, DevOps yoki ma'lumotlar bazasi yo'nalishi",
    [
        S(0, "SETUP", "Tayyorgarlik", 1, "1-2 soat", "Til tanlangan, muhit o'rnatilgan",
          [("Qaysi tildan boshlash?", "Bitta tilni tanlash: Python yoki JavaScript (Node.js)"), ("Kompyuter kuchsiz", "Brauzerdagi muhit yoki yengil muharrir")],
          ["30 daqiqa: Internet va server qanday ishlaydi", "30 daqiqa: Muhitni o'rnatish", "60 daqiqa: Birinchi kichik dastur"],
          ["Til tanlandi", "Kod muharriri ishlayapti", "Birinchi dastur ishga tushdi"],
          ["Har kuni boshqa til", "Faqat video ko'rish"],
          ["Muhit tayyor", "Server/so'rov tushunchasi", "Birinchi dastur"],
          ["Tanlov ko'pligi", "Terminal qo'rquvi"], ["Dasturlash muhiti", "Asosiy tushunchalar"]),
        S(1, "LANGUAGE BASICS", "Til asoslari", 4, "2 soat", "Kichik konsol ilova",
          [("Xatolar ko'p", "Xato matnini o'qish va qidirish odati"), ("Mavzu qiyin", "Kichik masalalarni har kuni yechish")],
          ["30 daqiqa: Yangi mavzu", "60 daqiqa: Masala yechish", "30 daqiqa: Takrorlash"],
          ["O'zgaruvchi, shart, sikl, funksiyani bilaman", "Kichik masalani o'zim yechaman", "Git'ga kod yuklayman"],
          ["Faqat tayyor kodni ko'chirish", "Xatodan qochish"],
          ["Konsol ilova (masalan, xarajatlar hisobi)", "Git va GitHub", "20+ yechilgan masala"],
          ["Mantiqni yo'qotish", "Sabr"], ["Python/JavaScript", "Git"]),
        S(2, "WEB + DATABASE", "Server va baza", 5, "2 soat", "Bazaga ulangan API",
          [("SQL notanish", "SQL'ni oddiy jadvallardan boshlash"), ("HTTP tushunarsiz", "Postman bilan so'rovlarni qo'lda yuborish")],
          ["30 daqiqa: HTTP va REST", "30 daqiqa: SQL", "60 daqiqa: API yozish"],
          ["GET/POST farqini bilaman", "SQL'da so'rov yozaman", "API bazadan ma'lumot qaytaradi"],
          ["Bazasiz faqat ro'yxat bilan ishlash", "Xatolarni tekshirmaslik"],
          ["CRUD API (masalan, vazifalar ro'yxati)", "SQL: SELECT, JOIN, INDEX asoslari", "Kirishni tekshirish (validatsiya)"],
          ["Baza tuzilishi", "Ko'p yangi tushuncha"], ["REST API", "SQL", "Framework asoslari"]),
        S(3, "REAL PROJECT", "Real loyiha", 6, "3 soat", "Internetga chiqarilgan loyiha",
          [("G'oya yo'q", "Tanish kichik biznes uchun buyurtma yoki navbat tizimi"), ("Deploy qiyin", "Bepul tarifli hosting bilan boshlash")],
          ["60 daqiqa: Loyiha kodi", "30 daqiqa: Test yozish", "30 daqiqa: Hujjat (README)"],
          ["Ro'yxatdan o'tish va kirish ishlaydi", "Testlar bor", "Loyiha internetda ochiladi"],
          ["Loyihani tugatmasdan yangisini boshlash", "Parolni ochiq saqlash"],
          ["Autentifikatsiya", "Avtomatik testlar", "Deploy qilingan loyiha", "README"],
          ["Xavfsizlik", "Loyihani oxiriga yetkazish"], ["Autentifikatsiya", "Testlash", "Deploy"]),
        S(4, "JOB READY", "Ishga tayyorlanish", 4, "3 soat", "Junior Backend ariza va suhbatlar",
          [("Tajriba yo'q", "Portfolio va GitHub tarixini ko'rsatish"), ("Suhbatdan qo'rqish", "Mashq suhbatlari va kod tushuntirish")],
          ["60 daqiqa: Portfolio", "60 daqiqa: Ariza", "60 daqiqa: Suhbatga tayyorgarlik"],
          ["Rezyume tayyor", "Har hafta arizalar yuboryapman", "Loyihamni og'zaki tushuntira olaman"],
          ["Faqat bitta joyga ariza", "Rad javobidan keyin to'xtash"],
          ["Rezyume + GitHub", "2–3 loyiha", "Muntazam arizalar", "Mashq suhbatlari"],
          ["Rad javoblari", "O'ziga ishonch"], ["Suhbat", "Portfolio"]),
    ],
    [W(1, "Asoslar", ["Til tanlash", "Muhit o'rnatish", "O'zgaruvchilar", "Shartlar", "Sikllar", "5 ta masala"]),
     W(2, "Funksiya va Git", ["Funksiyalar", "Ro'yxat va lug'at", "Git asoslari", "GitHub", "Xatolarni o'qish", "Konsol ilova"]),
     W(3, "HTTP va SQL", ["HTTP so'rovlari", "Postman", "SQL SELECT", "SQL JOIN", "Jadval loyihalash", "Mini baza"]),
     W(4, "Birinchi API", ["Framework o'rnatish", "GET endpoint", "POST endpoint", "Bazaga ulash", "Validatsiya", "API tayyor"])],
    ["Python yoki JavaScript'ni tanlash (bugun, 10 daqiqa)", "Kod muharririni o'rnatish (bugun, 20 daqiqa)", "Birinchi dasturni ishga tushirish (bugun, 30 daqiqa)"],
    MENTOR_GENERIC,
    [R("roadmap.sh — Backend", "https://roadmap.sh/backend"), R("freeCodeCamp", "https://www.freecodecamp.org/learn"), R("SQLBolt", "https://sqlbolt.com/")],
    [(1, "Muhit tayyor"), (5, "Konsol ilova"), (10, "Bazaga ulangan API"), (16, "Internetdagi loyiha"), (20, "Ariza va suhbatlar")],
)

P1["mobile_development"] = C(
    "Mobil dasturchi", "software", "Dasturlash",
    "Mobil dasturchi odamlar har kuni qo'lida ishlatadigan ilovani yaratadi. Telefonda qulay, tez va tushunarli narsa qurishni yoqtiradigan odam uchun.",
    ["Junior Mobile vakansiyalariga ariza berish", "Portfolio: 2 ta ishlaydigan ilova", "Freelance: kichik biznes uchun oddiy ilova"],
    "Middle Mobile yoki Frontend/Backend bilan full-stack",
    [
        S(0, "SETUP", "Tayyorgarlik", 1, "1-2 soat", "Platforma tanlangan, emulyator ishlayapti",
          [("Android yoki iOS?", "Kross-platforma (Flutter) yoki Android (Kotlin) bilan boshlash"), ("Kompyuter kuchsiz", "Emulyator o'rniga o'z telefonida sinash")],
          ["30 daqiqa: Ilova qanday ishlaydi", "30 daqiqa: Muhit o'rnatish", "60 daqiqa: Birinchi ekran"],
          ["Platforma tanlandi", "Ilova telefonda ochildi", "Birinchi ekran tayyor"],
          ["Ikki platformani birdan boshlash", "Faqat video ko'rish"],
          ["Muhit tayyor", "\"Salom\" ilovasi telefonda", "Platforma tanlangan"],
          ["O'rnatish qiyinligi", "Tanlov"], ["Mobil muhit", "Asosiy tushunchalar"]),
        S(1, "LANGUAGE + UI", "Til va ekranlar", 4, "2 soat", "3 ekranli ilova",
          [("Dart/Kotlin notanish", "Har kuni kichik mashq"), ("Dizayn qiyin", "Tayyor komponentlardan foydalanish")],
          ["30 daqiqa: Til asoslari", "60 daqiqa: Ekran yasash", "30 daqiqa: Takrorlash"],
          ["Tugma, ro'yxat, forma yasayman", "Ekranlar orasida o'taman", "Kodni Git'da saqlayman"],
          ["Faqat dizaynga berilish", "Kodni saqlamaslik"],
          ["3 ekranli ilova", "Navigatsiya", "Git va GitHub"],
          ["Ekran o'lchamlari", "Holat (state)"], ["Flutter/Kotlin", "UI komponentlar"]),
        S(2, "DATA + API", "Ma'lumot va internet", 5, "2 soat", "Internetdan ma'lumot oladigan ilova",
          [("API tushunarsiz", "Ochiq API'dan (masalan, ob-havo) boshlash"), ("Ma'lumot saqlash", "Telefon ichidagi oddiy baza")],
          ["30 daqiqa: HTTP va JSON", "60 daqiqa: Ilova kodi", "30 daqiqa: Xatolarni tuzatish"],
          ["API'dan ma'lumot olaman", "Ma'lumotni telefonda saqlayman", "Internet yo'qligini to'g'ri ko'rsataman"],
          ["Xatolarni e'tiborsiz qoldirish", "Hamma kod bitta faylda"],
          ["API bilan ilova", "Lokal saqlash", "Yuklanish va xato holatlari"],
          ["Asinxron kod", "Arxitektura"], ["HTTP/JSON", "Lokal baza", "Holatni boshqarish"]),
        S(3, "REAL APP", "Real ilova", 6, "3 soat", "Do'kon yoki test uchun tayyor ilova",
          [("G'oya yo'q", "O'zingiz yoki tanishingiz uchun foydali kichik ilova"), ("Do'konga chiqarish murakkab", "Avval test fayli (APK) bilan tanishlarga berish")],
          ["60 daqiqa: Ilova kodi", "30 daqiqa: Sinovchilardan fikr", "30 daqiqa: Tuzatish"],
          ["5+ kishi ilovani sinadi", "Fikrlar asosida tuzatdim", "Ilova barqaror ishlaydi"],
          ["Sinovchilarsiz ishlash", "Har kuni yangi funksiya qo'shish"],
          ["Tugallangan ilova", "Sinovchilar fikri", "Ekran rasmlari va tavsif"],
          ["Oxiriga yetkazish", "Turli telefonlar"], ["Relizga tayyorlash", "Foydalanuvchi fikri bilan ishlash"]),
        S(4, "JOB READY", "Ishga tayyorlanish", 4, "3 soat", "Junior Mobile ariza va suhbatlar",
          [("Tajriba yo'q", "Ilovalarni telefonda ko'rsatish"), ("Suhbatdan qo'rqish", "Mashq suhbatlari")],
          ["60 daqiqa: Portfolio", "60 daqiqa: Ariza", "60 daqiqa: Suhbatga tayyorgarlik"],
          ["Rezyume tayyor", "Har hafta arizalar", "Ilovamni tushuntira olaman"],
          ["Faqat bitta joyga ariza", "Rad javobidan keyin to'xtash"],
          ["Rezyume + GitHub", "2 ta ilova", "Muntazam arizalar"],
          ["Rad javoblari", "Raqobat"], ["Suhbat", "Portfolio"]),
    ],
    [W(1, "Muhit va til", ["Platforma tanlash", "Muhit o'rnatish", "Birinchi ekran", "O'zgaruvchilar", "Funksiyalar", "Kichik mashq"]),
     W(2, "Ekranlar", ["Tugma va matn", "Ro'yxat", "Forma", "Navigatsiya", "Git", "3 ekranli ilova"]),
     W(3, "Ma'lumot", ["JSON", "HTTP so'rov", "Ochiq API", "Yuklanish holati", "Xato holati", "API ilova"]),
     W(4, "Saqlash", ["Lokal saqlash", "Sozlamalar ekrani", "Holatni boshqarish", "Kod tartibi", "Sinovchiga berish", "Fikrlarni yig'ish"])],
    ["Flutter yoki Kotlin'ni tanlash (bugun, 10 daqiqa)", "Muhitni o'rnatishni boshlash (bugun, 40 daqiqa)", "Ilovani o'z telefoningizda ochish (bugun, 20 daqiqa)"],
    MENTOR_GENERIC,
    [R("Flutter — Get started", "https://docs.flutter.dev/get-started"), R("Android Developers — Courses", "https://developer.android.com/courses"), R("roadmap.sh — Android", "https://roadmap.sh/android")],
    [(1, "Ilova telefonda ochildi"), (5, "3 ekranli ilova"), (10, "API bilan ilova"), (16, "Sinovdan o'tgan ilova"), (20, "Ariza va suhbatlar")],
)

P1["qa_automation"] = C(
    "QA / test mutaxassisi", "software", "Dasturlash",
    "QA mutaxassisi mahsulot odamga yetib borishidan oldin xatolarni topadi. Diqqatli, \"bu yerda nima buzilishi mumkin?\" deb o'ylaydigan odam uchun.",
    ["Junior QA vakansiyalariga ariza berish", "Portfolio: test hujjatlari va avtotestlar", "Freelance test topshiriqlari"],
    "QA Automation, keyinchalik QA Lead yoki dasturlash",
    [
        S(0, "SETUP", "Tayyorgarlik", 1, "1-2 soat", "Test nima ekanini tushunish",
          [("Dasturlash bilmayman", "Qo'lda testdan boshlash — kod keyin"), ("Qayerda mashq qilaman?", "Mashq uchun mo'ljallangan ochiq saytlar")],
          ["30 daqiqa: Test turlari", "30 daqiqa: Xato hisoboti namunasi", "60 daqiqa: Ilovani sinab ko'rish"],
          ["Test turlarini ajrataman", "Birinchi xatoni topdim", "Hisobot yozdim"],
          ["Faqat nazariya", "Xatoni tushuntirmasdan yozish"],
          ["Test turlari", "1 ta xato hisoboti", "Mashq sayti tanlangan"],
          ["Qayerdan boshlash", "Atamalar"], ["Test asoslari"]),
        S(1, "MANUAL TESTING", "Qo'lda test", 4, "2 soat", "Test-keyslar to'plami",
          [("Nimani sinashni bilmayman", "Chegara qiymatlar va teng bo'linish usuli"), ("Hisobot tartibsiz", "Tayyor shablon: qadamlar, kutilgan, haqiqiy natija")],
          ["30 daqiqa: Usul o'rganish", "60 daqiqa: Test-keys yozish", "30 daqiqa: Xato hisoboti"],
          ["Test-keys yozaman", "Xatoni qayta takrorlash qadamlarini yozaman", "Jira/Trello'da ishlayman"],
          ["Faqat \"ishlamayapti\" deb yozish", "Bir xil testni takrorlash"],
          ["30+ test-keys", "10+ xato hisoboti", "Test rejasi"],
          ["Mayda detallar", "Bir xillik"], ["Test dizayn", "Bug report", "Jira/Trello"]),
        S(2, "WEB + API TESTING", "Veb va API test", 4, "2 soat", "Brauzer vositalari va API testlari",
          [("Brauzer vositalari notanish", "DevTools'da Network va Console"), ("API nima?", "Postman bilan oddiy so'rovlar")],
          ["30 daqiqa: DevTools", "30 daqiqa: SQL asoslari", "60 daqiqa: API test"],
          ["Network'da xatoni topaman", "Postman'da API sinayman", "Bazadan natijani tekshiraman"],
          ["Faqat ekranga qarash", "Server javobini tekshirmaslik"],
          ["API test to'plami", "SQL bilan tekshiruv", "DevTools hisobotlari"],
          ["Texnik atamalar", "Ko'p vosita"], ["DevTools", "Postman", "SQL"]),
        S(3, "AUTOMATION", "Avtotest", 6, "3 soat", "Avtotestlar to'plami",
          [("Kod yozish qiyin", "Python yoki JavaScript asoslaridan boshlash"), ("Testlar beqaror", "To'g'ri kutish va aniq lokatorlar")],
          ["30 daqiqa: Til asoslari", "60 daqiqa: Avtotest yozish", "30 daqiqa: Natijani tahlil"],
          ["Brauzerni kod bilan boshqaraman", "10+ avtotest yozdim", "Testlar GitHub'da"],
          ["Hamma narsani avtomatlashtirishga urinish", "Beqaror testlarni qoldirish"],
          ["Playwright/Selenium testlari", "GitHub loyiha", "Test hisoboti"],
          ["Dasturlash", "Barqarorlik"], ["Playwright/Selenium", "Python/JS asoslari"]),
        S(4, "JOB READY", "Ishga tayyorlanish", 4, "3 soat", "Junior QA ariza va suhbatlar",
          [("Tajriba yo'q", "Ochiq mahsulotlarni sinab, hisobotlarni portfolioga qo'shish"), ("Suhbat", "Test-keys yozishni jonli mashq qilish")],
          ["60 daqiqa: Portfolio", "60 daqiqa: Ariza", "60 daqiqa: Suhbatga tayyorgarlik"],
          ["Rezyume tayyor", "Har hafta arizalar", "Test jarayonini tushuntira olaman"],
          ["Portfoliosiz ariza", "Rad javobidan keyin to'xtash"],
          ["Rezyume", "Test hujjatlari portfoliosi", "Avtotest loyihasi"],
          ["Rad javoblari", "O'ziga ishonch"], ["Suhbat", "Portfolio"]),
    ],
    [W(1, "Test asoslari", ["Test nima", "Test turlari", "Test-keys", "Bug report", "Mashq sayti", "5 ta xato"]),
     W(2, "Test dizayn", ["Chegara qiymatlar", "Teng bo'linish", "Test rejasi", "Jira/Trello", "Regression", "20 test-keys"]),
     W(3, "Veb va API", ["DevTools Console", "DevTools Network", "Postman", "API javoblari", "SQL SELECT", "API to'plam"]),
     W(4, "Avtotestga kirish", ["Til asoslari", "Playwright o'rnatish", "Birinchi avtotest", "Lokatorlar", "Kutishlar", "5 avtotest"])],
    ["Test turlari haqida qisqa material o'qish (bugun, 20 daqiqa)", "Sevimli ilovangizda 1 ta xato yoki noqulaylik topish (bugun, 30 daqiqa)", "Uni qadamlar bilan hisobot qilib yozish (bugun, 20 daqiqa)"],
    MENTOR_GENERIC,
    [R("roadmap.sh — QA", "https://roadmap.sh/qa"), R("Playwright — Docs", "https://playwright.dev/docs/intro"), R("Selenium — Documentation", "https://www.selenium.dev/documentation/")],
    [(1, "Birinchi xato hisoboti"), (5, "30+ test-keys"), (9, "API testlari"), (15, "Avtotest loyiha"), (19, "Ariza va suhbatlar")],
)

P1["data_science"] = C(
    "AI va Data Science muhandisi", "data_ai", "Ma'lumotlar va sun'iy intellekt",
    "Data Science va AI — ma'lumotdan qonuniyat topib, bashorat qiladigan model qurish. Matematikadan qo'rqmaydigan, tajriba qilib natijani asta-sekin yaxshilashni yoqtiradigan odam uchun. Yo'l uzoqroq va matematika talab qiladi — buni oldindan bilish kerak.",
    ["Junior Data Scientist / ML stajyor vakansiyalariga ariza", "Portfolio: 3 ta model loyihasi", "Kaggle musobaqalarida qatnashish"],
    "ML Engineer yoki AI mahsulot jamoasi",
    [
        S(0, "SETUP", "Tayyorgarlik", 1, "1-2 soat", "Python muhiti va reja",
          [("Matematika esdan chiqqan", "Kerakli mavzularni yo'l davomida takrorlash"), ("Kompyuter kuchsiz", "Brauzerdagi bepul notebook muhiti")],
          ["30 daqiqa: AI va ML nima", "30 daqiqa: Notebook muhiti", "60 daqiqa: Birinchi Python kod"],
          ["Notebook ochildi", "Birinchi kod ishladi", "O'qish rejasi bor"],
          ["Darhol murakkab neyron tarmoqqa o'tish", "Faqat yangilik o'qish"],
          ["Muhit tayyor", "Reja", "Python'da birinchi qadam"],
          ["Mavzu kengligi", "Qo'rquv"], ["Notebook", "Asosiy tushunchalar"]),
        S(1, "PYTHON + MATH", "Python va matematika", 5, "2 soat", "Python va statistika asoslari",
          [("Statistika qiyin", "Har mavzuni kichik ma'lumotda sinab ko'rish"), ("Python yangi", "Har kuni kichik masala")],
          ["45 daqiqa: Python", "45 daqiqa: Statistika va ehtimollik", "30 daqiqa: Mashq"],
          ["Pandas bilan jadval o'qiyman", "O'rtacha, mediana, taqsimotni tushunaman", "Grafik chizaman"],
          ["Formulani tushunmasdan yodlash", "Mashqsiz o'qish"],
          ["Python asoslari", "Pandas", "Statistika asoslari", "Grafiklar"],
          ["Matematika", "Sabr"], ["Python", "Pandas", "Statistika"]),
        S(2, "MACHINE LEARNING", "Mashinali o'qitish", 6, "2-3 soat", "Birinchi modellar",
          [("Algoritmlar ko'p", "Avval 3 tasi: chiziqli regressiya, qaror daraxti, klasterlash"), ("Natija yomon", "Ma'lumotni tozalash va to'g'ri baholash")],
          ["30 daqiqa: Nazariya", "60 daqiqa: Model qurish", "30 daqiqa: Natijani baholash"],
          ["Ma'lumotni train/test'ga ajrataman", "Modelni baholayman", "Natijani tushuntiraman"],
          ["Test ma'lumotida o'qitish", "Faqat aniqlikka qarash"],
          ["3 ta model loyihasi", "Baholash metrikalari", "Natija hisoboti"],
          ["Overfitting", "Ma'lumot tozalash"], ["scikit-learn", "Model baholash"]),
        S(3, "REAL PROJECT", "Real loyiha", 6, "3 soat", "To'liq loyiha va tushuntirish",
          [("Ma'lumot topish", "Ochiq ma'lumotlar to'plamlari"), ("Loyiha chuqur emas", "Bitta savolga to'liq javob")],
          ["60 daqiqa: Loyiha", "30 daqiqa: Hujjat", "30 daqiqa: Kaggle"],
          ["Loyiha savoldan xulosagacha tugadi", "Natijani sodda tushuntirdim", "Kod GitHub'da"],
          ["Natijani bo'rttirish", "Tushuntirishsiz loyiha"],
          ["To'liq loyiha", "Notebook + hisobot", "1 ta musobaqada qatnashish"],
          ["Oxiriga yetkazish", "Tushuntirish"], ["End-to-end loyiha", "Taqdimot"]),
        S(4, "JOB READY", "Ishga tayyorlanish", 4, "3 soat", "Stajyor/junior ariza va suhbatlar",
          [("Junior o'rinlar kam", "Data analitik yoki stajyorlik orqali kirish"), ("Suhbat", "Loyihani 5 daqiqada tushuntirish mashqi")],
          ["60 daqiqa: Portfolio", "60 daqiqa: Ariza", "60 daqiqa: Suhbatga tayyorgarlik"],
          ["Rezyume tayyor", "Har hafta arizalar", "Loyihalarimni tushuntira olaman"],
          ["Faqat \"AI engineer\" o'rinlariga ariza", "Rad javobidan keyin to'xtash"],
          ["Rezyume + GitHub", "3 ta loyiha", "Muntazam arizalar"],
          ["Raqobat", "Tajriba talabi"], ["Suhbat", "Portfolio"]),
    ],
    [W(1, "Python asoslari", ["Notebook muhiti", "O'zgaruvchilar", "Ro'yxatlar", "Funksiyalar", "Fayl o'qish", "Kichik mashq"]),
     W(2, "Jadval bilan ishlash", ["Pandas o'rnatish", "Jadval o'qish", "Filtrlash", "Guruhlash", "Grafik", "Mini tahlil"]),
     W(3, "Statistika", ["O'rtacha va mediana", "Taqsimot", "Ehtimollik", "Korrelyatsiya", "Namuna", "Statistika mashqi"]),
     W(4, "Birinchi model", ["ML nima", "Train/test", "Chiziqli regressiya", "Baholash", "Xulosa yozish", "Birinchi model"])],
    ["Brauzerda bepul notebook ochish (bugun, 10 daqiqa)", "Kaggle Learn'dagi Python kursini boshlash (bugun, 40 daqiqa)", "Bir haftalik o'qish vaqtini kalendarga yozish (bugun, 10 daqiqa)"],
    MENTOR_GENERIC,
    [R("Kaggle Learn", "https://www.kaggle.com/learn"), R("Google — Machine Learning Crash Course", "https://developers.google.com/machine-learning/crash-course"), R("scikit-learn — Tutorials", "https://scikit-learn.org/stable/tutorial/index.html")],
    [(1, "Muhit tayyor"), (6, "Python va statistika"), (12, "3 ta model"), (18, "To'liq loyiha"), (22, "Ariza va suhbatlar")],
)

P1["database_specialist"] = C(
    "Ma'lumotlar bazasi mutaxassisi", "data_ai", "Ma'lumotlar va sun'iy intellekt",
    "Ma'lumotlar bazasi mutaxassisi kompaniya ma'lumotlarining tartibli, tez va xavfsiz saqlanishini ta'minlaydi. Tartibni yaxshi ko'radigan, ishonchlilikni qadrlaydigan odam uchun.",
    ["Junior DBA / SQL dasturchi vakansiyalariga ariza", "Portfolio: loyihalangan baza va so'rovlar to'plami", "Data yoki backend jamoasida stajyorlik"],
    "DBA, Data Engineer yoki Backend",
    [
        S(0, "SETUP", "Tayyorgarlik", 1, "1-2 soat", "PostgreSQL o'rnatilgan",
          [("Qaysi baza?", "PostgreSQL bilan boshlash"), ("O'rnatish qiyin", "Onlayn SQL mashq saytlari")],
          ["30 daqiqa: Baza nima", "30 daqiqa: O'rnatish", "60 daqiqa: Birinchi jadval"],
          ["Baza o'rnatildi", "Birinchi jadval yaratildi", "Birinchi so'rov ishladi"],
          ["Faqat nazariya", "Excel bilan adashtirish"],
          ["PostgreSQL tayyor", "1 ta jadval", "1 ta so'rov"],
          ["Atamalar", "O'rnatish"], ["SQL muhiti"]),
        S(1, "SQL BASICS", "SQL asoslari", 4, "2 soat", "Murakkab so'rovlar yozish",
          [("JOIN tushunarsiz", "Ikki kichik jadvalda qo'lda sinash"), ("Mashq yetmaydi", "Har kuni 5 ta masala")],
          ["30 daqiqa: Yangi mavzu", "60 daqiqa: Masalalar", "30 daqiqa: Takrorlash"],
          ["SELECT, WHERE, GROUP BY yozaman", "JOIN ishlataman", "Natijani tekshiraman"],
          ["Natijani tekshirmaslik", "Faqat oson masalalar"],
          ["50+ yechilgan masala", "JOIN va agregatlar", "Subquery"],
          ["Mantiq", "Aniqlik"], ["SQL", "JOIN", "Agregatlar"]),
        S(2, "DATABASE DESIGN", "Bazani loyihalash", 5, "2 soat", "To'g'ri tuzilgan baza",
          [("Jadvallar takrorlanadi", "Normalizatsiya qoidalari"), ("Bog'lanishlar chalkash", "ER-diagramma chizish")],
          ["30 daqiqa: Nazariya", "60 daqiqa: Loyihalash", "30 daqiqa: Sinash"],
          ["ER-diagramma chizaman", "Kalitlarni to'g'ri qo'yaman", "Takror ma'lumotdan qochaman"],
          ["Hamma narsa bitta jadvalda", "Kalitsiz jadvallar"],
          ["Do'kon yoki maktab bazasi loyihasi", "ER-diagramma", "Cheklovlar (constraints)"],
          ["Abstrakt fikrlash", "Ko'p qoida"], ["Normalizatsiya", "ER-diagramma"]),
        S(3, "PERFORMANCE + BACKUP", "Tezlik va zaxira", 6, "3 soat", "Tezlashtirilgan va zaxiralangan baza",
          [("So'rov sekin", "EXPLAIN va indekslar"), ("Zaxira qo'rqinchli", "Zaxira olish va tiklashni mashq qilish")],
          ["30 daqiqa: Indekslar", "60 daqiqa: Amaliyot", "30 daqiqa: Zaxira mashqi"],
          ["EXPLAIN'ni o'qiyman", "Indeks bilan so'rovni tezlashtirdim", "Zaxiradan tikladim"],
          ["Har ustunga indeks qo'yish", "Zaxirani sinamaslik"],
          ["Indekslash loyihasi", "Zaxira va tiklash", "Foydalanuvchi huquqlari"],
          ["Tezlik tahlili", "Xavfsizlik"], ["Indekslar", "Backup/restore", "Huquqlar"]),
        S(4, "JOB READY", "Ishga tayyorlanish", 4, "3 soat", "Junior ariza va suhbatlar",
          [("Junior DBA o'rinlari kam", "SQL dasturchi yoki data jamoasi orqali kirish"), ("Suhbat", "SQL masalalarni jonli yechish mashqi")],
          ["60 daqiqa: Portfolio", "60 daqiqa: Ariza", "60 daqiqa: SQL mashq"],
          ["Rezyume tayyor", "Har hafta arizalar", "Loyihamni tushuntira olaman"],
          ["Faqat DBA o'rinlariga ariza", "Rad javobidan keyin to'xtash"],
          ["Rezyume + GitHub", "Baza loyihasi", "Muntazam arizalar"],
          ["Tajriba talabi", "Raqobat"], ["Suhbat", "Portfolio"]),
    ],
    [W(1, "Baza asoslari", ["Baza nima", "O'rnatish", "Jadval yaratish", "INSERT", "SELECT", "10 masala"]),
     W(2, "So'rovlar", ["WHERE", "ORDER BY", "GROUP BY", "JOIN", "Subquery", "20 masala"]),
     W(3, "Loyihalash", ["Kalitlar", "Bog'lanishlar", "Normalizatsiya", "ER-diagramma", "Cheklovlar", "Mini baza"]),
     W(4, "Ishonchlilik", ["Indeks", "EXPLAIN", "Zaxira", "Tiklash", "Huquqlar", "Loyiha hisoboti"])],
    ["SQLBolt'ning birinchi 3 darsini o'tish (bugun, 40 daqiqa)", "PostgreSQL o'rnatish yoki onlayn muhit ochish (bugun, 20 daqiqa)", "O'z ro'yxatingizdan (kitoblar, xarajatlar) jadval yaratish (bugun, 20 daqiqa)"],
    MENTOR_GENERIC,
    [R("SQLBolt", "https://sqlbolt.com/"), R("PostgreSQL — Tutorial", "https://www.postgresql.org/docs/current/tutorial.html"), R("roadmap.sh — PostgreSQL DBA", "https://roadmap.sh/postgresql-dba")],
    [(1, "Birinchi jadval"), (5, "50+ SQL masala"), (10, "Loyihalangan baza"), (16, "Tezlik va zaxira"), (20, "Ariza va suhbatlar")],
)

P1["system_network_admin"] = C(
    "Tizim va tarmoq ma'muri", "infra_security", "Tizimlar, tarmoq va xavfsizlik",
    "Tizim va tarmoq ma'muri ofisdagi kompyuter, server va internetning uzluksiz ishlashini ta'minlaydi. Qo'l bilan ishlashni, buzilgan narsani tez tuzatishni yoqtiradigan odam uchun.",
    ["Helpdesk / IT support vakansiyalariga ariza", "Junior tizim ma'muri o'rinlari", "Kichik ofislarga xizmat ko'rsatish"],
    "Tizim muhandisi, DevOps yoki kiberxavfsizlik",
    [
        S(0, "SETUP", "Tayyorgarlik", 1, "1-2 soat", "Kompyuter va tarmoq asoslari",
          [("Uskuna yo'q", "Virtual mashina (VirtualBox) bilan mashq"), ("Atamalar ko'p", "Lug'at daftar")],
          ["30 daqiqa: Kompyuter qismlari", "30 daqiqa: Tarmoq nima", "60 daqiqa: Virtual mashina o'rnatish"],
          ["Virtual mashina ishlayapti", "IP manzilni topa olaman", "Atamalar lug'ati bor"],
          ["Faqat video ko'rish", "Amaliyotsiz o'qish"],
          ["Virtual mashina", "Asosiy atamalar", "IP manzil"],
          ["Atamalar", "Qayerdan boshlash"], ["Virtualizatsiya", "Asosiy tushunchalar"]),
        S(1, "OS + SUPPORT", "Operatsion tizimlar", 4, "2 soat", "Windows va Linux asoslari",
          [("Linux qo'rqinchli", "Har kuni 10 ta buyruq"), ("Muammoni qayerdan izlash", "Tekshiruv ro'yxati (checklist)")],
          ["30 daqiqa: Windows", "45 daqiqa: Linux buyruqlari", "45 daqiqa: Muammo hal qilish mashqi"],
          ["Foydalanuvchi va huquqlarni sozlayman", "Linux'da fayl va jarayonlar bilan ishlayman", "Muammoni bosqichma-bosqich tekshiraman"],
          ["Taxmin bilan tuzatish", "Qilganini yozib qo'ymaslik"],
          ["Windows sozlash", "Linux asoslari", "Muammo hal qilish checklisti"],
          ["Buyruqlar", "Mantiqiy tekshiruv"], ["Windows", "Linux", "Troubleshooting"]),
        S(2, "NETWORKING", "Tarmoq", 5, "2 soat", "Kichik tarmoqni sozlash",
          [("Tarmoq mavhum", "Uydagi routerdan boshlash"), ("Uskuna yo'q", "Tarmoq simulyatori")],
          ["30 daqiqa: Nazariya", "60 daqiqa: Simulyatorda mashq", "30 daqiqa: Takrorlash"],
          ["IP, DNS, DHCP'ni tushunaman", "Simulyatorda tarmoq qurdim", "ping va traceroute ishlataman"],
          ["Faqat yodlash", "Routerni tushunmasdan sozlash"],
          ["Ofis tarmog'i loyihasi", "IP rejalash", "Wi-Fi xavfsizligi"],
          ["Mavhum tushunchalar", "Ko'p protokol"], ["TCP/IP", "DNS/DHCP", "Router sozlash"]),
        S(3, "SERVERS + PRACTICE", "Server va amaliyot", 6, "3 soat", "Ishlaydigan server va hujjatlar",
          [("Real tajriba yo'q", "Tanish ofis yoki maktabga ko'ngilli yordam"), ("Hujjat yozish", "Qilingan ishni qadamma-qadam yozish odati")],
          ["60 daqiqa: Server sozlash", "30 daqiqa: Zaxira", "30 daqiqa: Hujjat"],
          ["Linux server sozladim", "Zaxira tizimini qurdim", "Real joyda yordam berdim"],
          ["Hujjatsiz ishlash", "Zaxirani sinamaslik"],
          ["Server (fayl yoki veb)", "Zaxira rejasi", "Real yordam tajribasi", "Ish hujjatlari"],
          ["Mas'uliyat", "Hujjat"], ["Linux server", "Backup", "Hujjatlash"]),
        S(4, "JOB READY", "Ishga tayyorlanish", 4, "3 soat", "Helpdesk / junior ariza va suhbatlar",
          [("Sertifikat yo'q", "Bepul kurs sertifikatlari va amaliy ish"), ("Suhbat", "Muammo hal qilish ssenariylarini mashq qilish")],
          ["60 daqiqa: Rezyume", "60 daqiqa: Ariza", "60 daqiqa: Suhbatga tayyorgarlik"],
          ["Rezyume tayyor", "Har hafta arizalar", "Muammo hal qilishni tushuntira olaman"],
          ["Faqat \"tizim ma'muri\" o'rinlariga ariza", "Rad javobidan keyin to'xtash"],
          ["Rezyume", "Amaliy ishlar ro'yxati", "Muntazam arizalar"],
          ["Tajriba talabi", "Navbatchilik"], ["Suhbat", "Rezyume"]),
    ],
    [W(1, "Asoslar", ["Kompyuter qismlari", "Virtual mashina", "Windows sozlash", "Foydalanuvchilar", "IP manzil", "Mashq"]),
     W(2, "Linux", ["Terminal", "Fayllar", "Huquqlar", "Jarayonlar", "Paketlar", "10 buyruq mashqi"]),
     W(3, "Tarmoq", ["IP va subnet", "DNS", "DHCP", "Router", "Wi-Fi xavfsizligi", "Simulyator"]),
     W(4, "Muammo hal qilish", ["Checklist", "ping/traceroute", "Printer muammosi", "Internet muammosi", "Hujjat", "Ssenariy mashqi"])],
    ["VirtualBox o'rnatish (bugun, 20 daqiqa)", "Kompyuteringizning IP manzilini topish (bugun, 10 daqiqa)", "Linux Journey'ning birinchi darsini o'tish (bugun, 30 daqiqa)"],
    MENTOR_GENERIC,
    [R("Cisco Networking Academy", "https://www.netacad.com/"), R("Linux Journey", "https://linuxjourney.com/"), R("Microsoft Learn", "https://learn.microsoft.com/en-us/training/")],
    [(1, "Virtual mashina"), (5, "Windows va Linux asoslari"), (10, "Tarmoq loyihasi"), (16, "Server va real yordam"), (20, "Ariza va suhbatlar")],
)

P1["devops_cloud"] = C(
    "DevOps / Cloud muhandisi", "infra_security", "Tizimlar, tarmoq va xavfsizlik",
    "DevOps muhandisi dasturning tez, avtomatik va ishonchli ishga tushishini ta'minlaydi. Takroriy ishni avtomatlashtirishni yoqtiradigan odam uchun. Odatda Linux, tarmoq va dasturlash asoslari oldindan kerak bo'ladi.",
    ["Junior DevOps / Cloud stajyorlik", "Tizim ma'muri yoki backend orqali o'tish", "Portfolio: avtomatlashtirilgan loyiha"],
    "DevOps/SRE yoki Cloud arxitektor",
    [
        S(0, "SETUP", "Tayyorgarlik", 1, "1-2 soat", "Linux muhiti va reja",
          [("Linux bilmayman", "Linux asoslaridan boshlash"), ("Kompyuter kuchsiz", "Virtual mashina yoki bulutdagi bepul sinov")],
          ["30 daqiqa: DevOps nima", "30 daqiqa: Linux muhiti", "60 daqiqa: Terminal"],
          ["Linux muhiti bor", "Terminalda ishlayman", "Reja tuzildi"],
          ["Darhol Kubernetes'ga o'tish", "Faqat atamalarni yodlash"],
          ["Linux muhiti", "Terminal asoslari", "O'qish rejasi"],
          ["Mavzu kengligi", "Atamalar"], ["Linux muhiti"]),
        S(1, "LINUX + SCRIPTING", "Linux va skript", 4, "2 soat", "Avtomatlashtiruvchi skriptlar",
          [("Skript qiyin", "Kichik takroriy ishdan boshlash"), ("Xatolar", "Loglarni o'qish odati")],
          ["30 daqiqa: Linux", "60 daqiqa: Bash/Python skript", "30 daqiqa: Git"],
          ["Bash skript yozaman", "Cron bilan vazifa rejalashtiraman", "Git ishlataman"],
          ["Qo'lda takrorlash", "Skriptni sinamaslik"],
          ["5+ foydali skript", "Git va GitHub", "Loglar bilan ishlash"],
          ["Sintaksis", "Mantiq"], ["Bash", "Git", "Cron"]),
        S(2, "CONTAINERS + CI/CD", "Konteyner va avtomatik chiqarish", 5, "2-3 soat", "Docker va CI/CD pipeline",
          [("Docker tushunarsiz", "Bitta oddiy ilovani konteynerga solish"), ("Pipeline murakkab", "Avval faqat test bosqichi")],
          ["30 daqiqa: Nazariya", "60 daqiqa: Docker", "30 daqiqa: CI/CD"],
          ["Dockerfile yozaman", "docker compose bilan ko'p servis", "Push'dan keyin testlar o'zi ishlaydi"],
          ["Konteynerga hamma narsani tiqish", "Maxfiy kalitni kodda saqlash"],
          ["Docker'dagi ilova", "CI/CD pipeline", "Maxfiy kalitlarni to'g'ri saqlash"],
          ["Ko'p yangi vosita", "Xatolarni topish"], ["Docker", "CI/CD", "Secrets"]),
        S(3, "CLOUD + MONITORING", "Bulut va kuzatuv", 6, "3 soat", "Bulutda ishlaydigan, kuzatiladigan loyiha",
          [("Bulut pullik", "Bepul sinov limitlari va xarajat ogohlantirishi"), ("Kuzatuv yo'q", "Oddiy monitoring va alertlar")],
          ["60 daqiqa: Bulut", "30 daqiqa: Monitoring", "30 daqiqa: Hujjat"],
          ["Ilovani bulutga joyladim", "Monitoring va ogohlantirish bor", "Infratuzilma kod bilan yozilgan"],
          ["Xarajat limitisiz ishlash", "Hujjatsiz infratuzilma"],
          ["Bulutdagi loyiha", "Monitoring", "Infrastructure as Code asoslari"],
          ["Xarajat", "Murakkablik"], ["Cloud asoslari", "Monitoring", "Terraform asoslari"]),
        S(4, "JOB READY", "Ishga tayyorlanish", 4, "3 soat", "Stajyorlik/junior ariza va suhbatlar",
          [("Junior DevOps o'rinlari kam", "Tizim ma'muri yoki backend orqali kirish"), ("Suhbat", "Loyiha arxitekturasini chizib tushuntirish")],
          ["60 daqiqa: Portfolio", "60 daqiqa: Ariza", "60 daqiqa: Suhbatga tayyorgarlik"],
          ["Rezyume tayyor", "Har hafta arizalar", "Pipeline'imni tushuntira olaman"],
          ["Faqat DevOps o'rinlariga ariza", "Rad javobidan keyin to'xtash"],
          ["Rezyume + GitHub", "Avtomatlashtirilgan loyiha", "Muntazam arizalar"],
          ["Tajriba talabi", "Raqobat"], ["Suhbat", "Portfolio"]),
    ],
    [W(1, "Linux", ["Terminal", "Fayllar", "Huquqlar", "Jarayonlar", "Tarmoq buyruqlari", "Mashq"]),
     W(2, "Skript", ["Bash asoslari", "O'zgaruvchi va sikl", "Cron", "Git", "Loglar", "Foydali skript"]),
     W(3, "Docker", ["Konteyner nima", "Image va container", "Dockerfile", "Volume", "Compose", "Docker loyiha"]),
     W(4, "CI/CD", ["Pipeline nima", "Test bosqichi", "Build bosqichi", "Secrets", "Deploy bosqichi", "Ishlaydigan pipeline"])],
    ["Linux muhitini tayyorlash (bugun, 30 daqiqa)", "roadmap.sh'dagi DevOps xaritasini ko'rib chiqish (bugun, 15 daqiqa)", "Takroriy bitta ishingizni yozib qo'yish — keyin avtomatlashtirasiz (bugun, 10 daqiqa)"],
    MENTOR_GENERIC,
    [R("roadmap.sh — DevOps", "https://roadmap.sh/devops"), R("Docker — Get started", "https://docs.docker.com/get-started/"), R("Linux Journey", "https://linuxjourney.com/")],
    [(1, "Linux muhiti"), (5, "Foydali skriptlar"), (10, "Docker va CI/CD"), (16, "Bulutdagi loyiha"), (20, "Ariza va suhbatlar")],
)
