from h import S, W, R, C, MENTOR_GENERIC

P2 = {}

P2["cybersecurity"] = C(
    "Kiberxavfsizlik mutaxassisi", "infra_security", "Tizimlar, tarmoq va xavfsizlik",
    "Kiberxavfsizlik mutaxassisi tizim va ma'lumotlarni hujumlardan himoya qiladi. Hushyor, \"buni qanday buzish mumkin?\" deb o'ylaydigan va qoidaga rioya qiladigan odam uchun. Tarmoq va Linux asoslari oldindan kerak.",
    ["SOC tahlilchi (1-bosqich) yoki IT support orqali kirish", "Portfolio: laboratoriya hisobotlari", "CTF musobaqalarida qatnashish"],
    "SOC tahlilchi, pentest yoki xavfsizlik muhandisi",
    [
        S(0, "SETUP", "Tayyorgarlik", 1, "1-2 soat", "Xavfsiz mashq muhiti va qoidalar",
          [("Qonuniy chegara", "Faqat ruxsat berilgan laboratoriya va musobaqa muhitida mashq qilish"), ("Bilim yo'q", "Asoslardan boshlash")],
          ["30 daqiqa: Kiberxavfsizlik nima", "30 daqiqa: Etika va qonun", "60 daqiqa: Laboratoriya muhiti"],
          ["Mashq platformasida akkaunt bor", "Qonuniy chegarani bilaman", "Reja tuzildi"],
          ["Begona tizimni sinab ko'rish", "Faqat film va video"],
          ["Mashq muhiti", "Etika qoidalari", "O'qish rejasi"],
          ["Qayerdan boshlash", "Qonuniy chegara"], ["Xavfsizlik asoslari"]),
        S(1, "NETWORK + LINUX", "Tarmoq va Linux", 5, "2 soat", "Tarmoq va Linux asoslari",
          [("Tarmoq mavhum", "Wireshark bilan o'z trafigingizni kuzatish"), ("Linux yangi", "Har kuni buyruqlar mashqi")],
          ["45 daqiqa: Tarmoq", "45 daqiqa: Linux", "30 daqiqa: Laboratoriya"],
          ["TCP/IP va portlarni tushunaman", "Linux'da erkin ishlayman", "Trafikni tahlil qila olaman"],
          ["Asoslarni o'tkazib yuborish", "Faqat vosita ishlatish"],
          ["Tarmoq asoslari", "Linux asoslari", "Wireshark mashqi"],
          ["Ko'p asos bilim", "Sabr"], ["TCP/IP", "Linux", "Wireshark"]),
        S(2, "SECURITY BASICS", "Xavfsizlik asoslari", 5, "2 soat", "Asosiy hujum va himoya turlari",
          [("Hujum turlari ko'p", "OWASP Top 10 dan boshlash"), ("Amaliyot yo'q", "Laboratoriya xonalari")],
          ["30 daqiqa: Nazariya", "60 daqiqa: Laboratoriya", "30 daqiqa: Hisobot"],
          ["Fishingni taniyman", "OWASP Top 10 ni tushuntira olaman", "Laboratoriya hisobotini yozaman"],
          ["Hisobotsiz mashq", "Vosita ortidan quvish"],
          ["10+ laboratoriya", "OWASP Top 10", "Hisobot namunalari"],
          ["Texnik chuqurlik", "Tartib"], ["OWASP", "Zaifliklarni aniqlash"]),
        S(3, "BLUE TEAM PRACTICE", "Himoya amaliyoti", 6, "3 soat", "Loglar tahlili va hodisaga javob",
          [("Loglar ko'p", "Bitta hodisani boshidan oxirigacha tekshirish"), ("Real tajriba yo'q", "SOC mashqlari va CTF")],
          ["60 daqiqa: Log tahlili", "30 daqiqa: CTF", "30 daqiqa: Hisobot"],
          ["Logda shubhali harakatni topaman", "Hodisaga javob qadamlarini bilaman", "CTF'da qatnashdim"],
          ["Faqat hujum tomoni", "Hisobot yozmaslik"],
          ["Log tahlili loyihasi", "Hodisa hisoboti", "1+ CTF"],
          ["Diqqat", "Hujjat"], ["SIEM asoslari", "Incident response"]),
        S(4, "JOB READY", "Ishga tayyorlanish", 4, "3 soat", "SOC / IT support ariza va suhbatlar",
          [("Junior o'rinlar kam", "IT support yoki tizim ma'muri orqali kirish"), ("Suhbat", "Hodisa ssenariylarini mashq qilish")],
          ["60 daqiqa: Portfolio", "60 daqiqa: Ariza", "60 daqiqa: Suhbatga tayyorgarlik"],
          ["Rezyume tayyor", "Har hafta arizalar", "Laboratoriya ishlarimni tushuntira olaman"],
          ["Faqat pentest o'rinlariga ariza", "Rad javobidan keyin to'xtash"],
          ["Rezyume", "Laboratoriya hisobotlari", "Muntazam arizalar"],
          ["Tajriba talabi", "Ishonch"], ["Suhbat", "Portfolio"]),
    ],
    [W(1, "Asoslar va etika", ["Kiberxavfsizlik nima", "Qonun va etika", "Mashq platformasi", "Parollar", "Fishing", "Birinchi xona"]),
     W(2, "Tarmoq", ["IP va portlar", "TCP/UDP", "DNS", "Wireshark", "Trafik tahlili", "Tarmoq xonasi"]),
     W(3, "Linux", ["Terminal", "Fayllar va huquqlar", "Jarayonlar", "Loglar", "Foydalanuvchilar", "Linux xonasi"]),
     W(4, "Veb xavfsizlik", ["OWASP Top 10", "Inyeksiya", "Autentifikatsiya", "XSS", "Hisobot yozish", "Veb xonasi"])],
    ["TryHackMe yoki Cisco NetAcad'da akkaunt ochish (bugun, 10 daqiqa)", "Kiberxavfsizlikda etika va qonun haqida o'qish (bugun, 20 daqiqa)", "Birinchi bepul laboratoriya xonasini boshlash (bugun, 40 daqiqa)"],
    MENTOR_GENERIC,
    [R("TryHackMe", "https://tryhackme.com/"), R("Cisco Networking Academy", "https://www.netacad.com/"), R("OWASP Top 10", "https://owasp.org/www-project-top-ten/")],
    [(1, "Mashq muhiti"), (6, "Tarmoq va Linux"), (11, "10+ laboratoriya"), (17, "Log tahlili va CTF"), (21, "Ariza va suhbatlar")],
)

P2["graphic_design"] = C(
    "Grafik dizayner", "design_creative", "Raqamli dizayn",
    "Grafik dizayner rang, shrift va obraz orqali brendni tanitadi: logotip, post, afisha, qadoq. Didli, fikrini rasm bilan ifodalashni yoqtiradigan odam uchun.",
    ["Junior grafik dizayner vakansiyalariga ariza", "Freelance: logotip va post buyurtmalari", "Agentlikda stajyorlik"],
    "Brend dizayn, motion yoki UI/UX",
    [
        S(0, "SETUP", "Tayyorgarlik", 1, "1-2 soat", "Vosita tanlangan, ilhom papkasi tayyor",
          [("Pullik dasturlar", "Bepul vositalar (Canva, Figma, Photopea) bilan boshlash"), ("Chiza olmayman", "Grafik dizayn rasm chizish emas — kompozitsiya va tartib")],
          ["30 daqiqa: Dizayn turlari", "30 daqiqa: Vosita o'rnatish", "60 daqiqa: Namunalar yig'ish"],
          ["Vosita tanlandi", "Ilhom papkasi bor", "Birinchi eskiz"],
          ["Faqat tomosha", "Ko'chirish"],
          ["Vosita", "Ilhom papkasi", "Birinchi eskiz"],
          ["O'ziga ishonch", "Tanlov"], ["Dizayn vositasi"]),
        S(1, "DESIGN BASICS", "Dizayn asoslari", 4, "2 soat", "Kompozitsiya, rang va shrift",
          [("Rang tanlash qiyin", "Tayyor palitra va rang qoidalari"), ("Shriftlar ko'p", "Bitta dizaynda 2 tadan ko'p emas")],
          ["30 daqiqa: Nazariya", "60 daqiqa: Mashq", "30 daqiqa: Tahlil"],
          ["Kompozitsiya qoidalarini qo'llayman", "Rang uyg'unligini tanlayman", "Shriftlarni to'g'ri juftlayman"],
          ["Hamma rangni ishlatish", "Bo'sh joydan qo'rqish"],
          ["10+ mashq ishi", "Rang va shrift qoidalari", "Kompozitsiya"],
          ["Did", "Sabr"], ["Kompozitsiya", "Rang", "Tipografika"]),
        S(2, "TOOLS + BRAND", "Vositalar va brend", 5, "2 soat", "Logotip va brend uslubi",
          [("Illustrator qiyin", "Figma'da vektor bilan boshlash"), ("G'oya yo'q", "Xayoliy brend uchun ishlash")],
          ["30 daqiqa: Vosita", "60 daqiqa: Brend loyiha", "30 daqiqa: Fikr so'rash"],
          ["Vektorda logotip chizaman", "Brend uslub qo'llanmasi tuzaman", "Fikr asosida qayta ishlayman"],
          ["Bitta variant bilan to'xtash", "Fikrdan xafa bo'lish"],
          ["2 ta xayoliy brend", "Logotip + uslub qo'llanmasi", "Post shablonlari"],
          ["Ko'p variant", "Tanqid"], ["Vektor grafika", "Brend identifikatsiyasi"]),
        S(3, "REAL CLIENT", "Birinchi mijoz", 6, "3 soat", "Real buyurtma va keys",
          [("Mijoz topish", "Tanish kichik biznes yoki tadbir"), ("Brif tushunarsiz", "Boshida savollar ro'yxati bilan brif olish")],
          ["30 daqiqa: Mijoz bilan aloqa", "60 daqiqa: Dizayn", "30 daqiqa: Keys yozish"],
          ["1+ real buyurtma", "Brif bilan ishladim", "Keys yozdim"],
          ["Brifsiz ishlash", "Cheksiz tuzatish"],
          ["1+ real ish", "Keys: vazifa → jarayon → natija", "Tuzatishlar soni kelishilgan"],
          ["Mijoz bilan muloqot", "Muddat"], ["Brif", "Mijoz bilan ishlash"]),
        S(4, "JOB READY", "Ishga tayyorlanish", 4, "3 soat", "Portfolio va arizalar",
          [("Portfolio tartibsiz", "Eng yaxshi 6–8 ish, har biri keys bilan"), ("Narx belgilash", "Ish hajmi va vaqtga qarab hisoblash")],
          ["60 daqiqa: Portfolio", "60 daqiqa: Ariza", "60 daqiqa: Networking"],
          ["Portfolio onlayn", "Har hafta arizalar", "Ishimni tushuntira olaman"],
          ["Hamma ishni portfolioga qo'yish", "Rad javobidan keyin to'xtash"],
          ["Portfolio (Behance yoki sayt)", "6–8 keys", "Muntazam arizalar"],
          ["Raqobat", "Narx"], ["Portfolio", "Taqdimot"]),
    ],
    [W(1, "Asoslar", ["Dizayn turlari", "Vosita o'rnatish", "Kompozitsiya", "Bo'sh joy", "Ilhom papkasi", "Birinchi post"]),
     W(2, "Rang va shrift", ["Rang doirasi", "Palitra", "Kontrast", "Shrift turlari", "Shrift juftligi", "Afisha"]),
     W(3, "Logotip", ["Logotip turlari", "Eskiz", "Vektor", "Variantlar", "Fikr so'rash", "Logotip"]),
     W(4, "Brend", ["Uslub qo'llanmasi", "Post shabloni", "Story shabloni", "Taqdimot", "Keys yozish", "Brend loyiha"])],
    ["Bepul dizayn vositasida akkaunt ochish (bugun, 10 daqiqa)", "Yoqqan 20 ta dizaynni bitta papkaga yig'ish (bugun, 30 daqiqa)", "Birinchi oddiy afishani yasash (bugun, 30 daqiqa)"],
    MENTOR_GENERIC,
    [R("Canva Design School", "https://www.canva.com/designschool/"), R("Google Fonts — Knowledge", "https://fonts.google.com/knowledge"), R("Figma — Help Center", "https://help.figma.com/")],
    [(1, "Birinchi afisha"), (5, "10+ mashq ishi"), (10, "2 ta brend loyiha"), (16, "Real buyurtma"), (20, "Portfolio va arizalar")],
)

P2["performance_marketing"] = C(
    "Target (performance) marketolog", "digital_marketing", "Raqamli marketing",
    "Target marketolog reklamani kerakli odamga ko'rsatib, har sarflangan pulning natijasini hisoblaydi. Raqamlarni, solishtirib sinashni va aniq natijani yoqtiradigan odam uchun.",
    ["Junior target/performance vakansiyalariga ariza", "Freelance: kichik biznes reklamasi", "Agentlikda stajyorlik"],
    "Performance lead yoki marketing analitika",
    [
        S(0, "SETUP", "Tayyorgarlik", 1, "1-2 soat", "Reklama kabinetlari bilan tanishuv",
          [("Reklama budjeti yo'q", "Avval bepul o'quv kurslari va demo kabinetlar"), ("Atamalar ko'p", "Asosiy ko'rsatkichlar lug'ati")],
          ["30 daqiqa: Reklama qanday ishlaydi", "30 daqiqa: Kabinet bilan tanishuv", "60 daqiqa: Reklamalarni tahlil"],
          ["Asosiy ko'rsatkichlarni bilaman", "Kabinetni ochdim", "10 ta reklamani tahlil qildim"],
          ["Darhol pul sarflash", "Faqat nazariya"],
          ["Ko'rsatkichlar lug'ati", "Kabinet", "Reklama tahlili"],
          ["Atamalar", "Qo'rquv"], ["Reklama asoslari"]),
        S(1, "PLATFORMS", "Reklama platformalari", 4, "2 soat", "Meta va Google kurslari",
          [("Platforma murakkab", "Rasmiy bepul kurslar"), ("Auditoriya tanlash", "Mijoz portretini yozishdan boshlash")],
          ["45 daqiqa: Kurs", "45 daqiqa: Kabinetda mashq", "30 daqiqa: Tahlil"],
          ["Kampaniya tuzilishini bilaman", "Auditoriya sozlayman", "Reklama matni va rasmini tanlayman"],
          ["Auditoriyani juda keng qo'yish", "Maqsadsiz kampaniya"],
          ["Meta va Google kurslari", "Mijoz portreti", "Mashq kampaniyalar"],
          ["Ko'p sozlama", "Mantiq"], ["Meta Ads", "Google Ads", "Auditoriya"]),
        S(2, "ANALYTICS + TESTING", "Analitika va sinov", 5, "2 soat", "Natijani o'lchash va A/B sinov",
          [("Natija o'lchanmaydi", "Analitika va konversiya kuzatuvini o'rnatish"), ("Qaysi reklama yaxshi?", "Bir vaqtda faqat bitta narsani o'zgartirish")],
          ["30 daqiqa: Analitika", "60 daqiqa: Sinov rejasi", "30 daqiqa: Hisobot"],
          ["Konversiyani kuzataman", "A/B sinov qilaman", "Hisobot tayyorlayman"],
          ["Bir vaqtda ko'p narsani o'zgartirish", "Faqat ko'rishlar soniga qarash"],
          ["Analitika sozlangan", "2+ A/B sinov", "Haftalik hisobot"],
          ["Raqamlar", "Sabr"], ["Google Analytics", "A/B test", "Hisobot"]),
        S(3, "REAL CLIENT", "Birinchi mijoz", 6, "3 soat", "Real kampaniya va keys",
          [("Mijoz topish", "Tanish kichik biznes, kichik budjet"), ("Natija kafolati so'raladi", "Natijani va'da qilmasdan, jarayon va hisobotni kelishish")],
          ["30 daqiqa: Mijoz bilan aloqa", "60 daqiqa: Kampaniya", "30 daqiqa: Hisobot"],
          ["1+ real kampaniya", "Har hafta hisobot", "Keys yozdim"],
          ["Natijani bo'rttirish", "Hisobotsiz ishlash"],
          ["Real kampaniya", "Keys: maqsad → sinov → natija", "Mijoz fikri"],
          ["Mas'uliyat", "Budjet"], ["Mijoz bilan ishlash", "Optimallashtirish"]),
        S(4, "JOB READY", "Ishga tayyorlanish", 4, "3 soat", "Portfolio va arizalar",
          [("Tajriba kam", "Keyslarni raqamlari bilan halol ko'rsatish"), ("Suhbat", "Kampaniya tahlilini jonli tushuntirish")],
          ["60 daqiqa: Portfolio", "60 daqiqa: Ariza", "60 daqiqa: Suhbatga tayyorgarlik"],
          ["Portfolio tayyor", "Har hafta arizalar", "Keyslarni tushuntira olaman"],
          ["Natijalarni o'ylab topish", "Rad javobidan keyin to'xtash"],
          ["Rezyume", "2–3 keys", "Muntazam arizalar"],
          ["Raqobat", "Tajriba talabi"], ["Suhbat", "Portfolio"]),
    ],
    [W(1, "Asoslar", ["Reklama qanday ishlaydi", "Ko'rsatkichlar", "Voronka", "Mijoz portreti", "Raqiblar reklamasi", "Tahlil"]),
     W(2, "Meta", ["Blueprint kursi", "Kampaniya tuzilishi", "Auditoriya", "Kreativ", "Reklama matni", "Mashq kampaniya"]),
     W(3, "Google", ["Skillshop kursi", "Qidiruv reklamasi", "Kalit so'zlar", "Reklama matni", "Sozlamalar", "Mashq kampaniya"]),
     W(4, "Analitika", ["Google Analytics", "Konversiya", "A/B sinov", "Hisobot", "Xulosa", "Haftalik hisobot"])],
    ["Meta Blueprint'da bepul kursni boshlash (bugun, 30 daqiqa)", "Telefoningizda ko'rgan 5 ta reklamani yozib, nega sizga chiqqanini o'ylash (bugun, 20 daqiqa)", "Asosiy ko'rsatkichlar lug'atini tuzish (bugun, 20 daqiqa)"],
    MENTOR_GENERIC,
    [R("Meta Blueprint", "https://www.facebook.com/business/learn"), R("Google Skillshop", "https://skillshop.withgoogle.com/"), R("Google Analytics — Help", "https://support.google.com/analytics")],
    [(1, "Ko'rsatkichlar lug'ati"), (5, "Meta va Google kurslari"), (10, "A/B sinov va hisobot"), (16, "Real kampaniya"), (20, "Portfolio va arizalar")],
)

P2["seo"] = C(
    "SEO mutaxassisi", "digital_marketing", "Raqamli marketing",
    "SEO mutaxassisi saytni odamlar qidiruvda topadigan qiladi. Natijani sabr bilan kutadigan, so'z va tartibga e'tiborli odam uchun. SEO natijasi odatda haftalar va oylar ichida ko'rinadi.",
    ["Junior SEO vakansiyalariga ariza", "Freelance: kichik biznes saytlari", "Agentlikda stajyorlik"],
    "SEO lead, kontent strategiya yoki marketing analitika",
    [
        S(0, "SETUP", "Tayyorgarlik", 1, "1-2 soat", "Qidiruv qanday ishlashini tushunish",
          [("Sayt yo'q", "Bepul blog ochib, unda mashq qilish"), ("Atamalar", "SEO lug'ati")],
          ["30 daqiqa: Qidiruv tizimi qanday ishlaydi", "30 daqiqa: Blog ochish", "60 daqiqa: Raqib saytlar tahlili"],
          ["Qidiruv tizimi ishlashini tushuntira olaman", "Mashq sayti bor", "SEO lug'ati bor"],
          ["Faqat nazariya", "Tez natija kutish"],
          ["Mashq sayti", "SEO lug'ati", "Raqiblar tahlili"],
          ["Atamalar", "Sabr"], ["SEO asoslari"]),
        S(1, "KEYWORDS + CONTENT", "Kalit so'z va kontent", 4, "2 soat", "Kalit so'zlar ro'yxati va maqolalar",
          [("Qaysi so'zlarni tanlash?", "Odamlar haqiqatan qidiradigan so'zlarni vositalar bilan tekshirish"), ("Yozish qiyin", "Avval reja, keyin matn")],
          ["30 daqiqa: Kalit so'z tadqiqoti", "60 daqiqa: Maqola yozish", "30 daqiqa: Tahrir"],
          ["Kalit so'zlar ro'yxati bor", "Sarlavha va tavsifni to'g'ri yozaman", "3+ maqola chiqardim"],
          ["Kalit so'zni haddan tashqari takrorlash", "Ko'chirilgan matn"],
          ["Kalit so'zlar ro'yxati", "3+ optimallashtirilgan maqola", "Sarlavha va meta tavsif"],
          ["Yozish", "Tanlov"], ["Kalit so'z tadqiqoti", "On-page SEO"]),
        S(2, "TECHNICAL SEO", "Texnik SEO", 5, "2 soat", "Sayt texnik auditi",
          [("Texnik tomonlar qiyin", "Search Console xabarlaridan boshlash"), ("Sayt sekin", "Tezlikni o'lchash vositalari")],
          ["30 daqiqa: Nazariya", "60 daqiqa: Audit", "30 daqiqa: Tuzatish rejasi"],
          ["Search Console bilan ishlayman", "Sayt tezligini tekshiraman", "Audit hisobotini yozaman"],
          ["Hamma xatoni birdan tuzatishga urinish", "Ustuvorliksiz ro'yxat"],
          ["Search Console sozlangan", "Texnik audit hisoboti", "Tuzatish rejasi"],
          ["Texnik atamalar", "Ustuvorlik"], ["Search Console", "Texnik audit"]),
        S(3, "REAL PROJECT", "Real loyiha", 6, "3 soat", "Real sayt bilan ishlash va keys",
          [("Mijoz topish", "Tanish kichik biznesning sayti yoki Google xaritadagi sahifasi"), ("Natija sekin", "Har hafta o'lchab, yozib borish")],
          ["30 daqiqa: Mijoz bilan aloqa", "60 daqiqa: Optimallashtirish", "30 daqiqa: Hisobot"],
          ["1+ real sayt ustida ishladim", "Har hafta ko'rsatkichlarni yozaman", "Keys yozdim"],
          ["Natijani va'da qilish", "O'lchovsiz ishlash"],
          ["Real loyiha", "Haftalik hisobot", "Keys"],
          ["Sabr", "Mijoz kutishi"], ["Mahalliy SEO", "Hisobot"]),
        S(4, "JOB READY", "Ishga tayyorlanish", 4, "3 soat", "Portfolio va arizalar",
          [("Natija hali kichik", "Jarayon va qilingan ishni halol ko'rsatish"), ("Suhbat", "Audit namunasini tushuntirish")],
          ["60 daqiqa: Portfolio", "60 daqiqa: Ariza", "60 daqiqa: Suhbatga tayyorgarlik"],
          ["Portfolio tayyor", "Har hafta arizalar", "Auditimni tushuntira olaman"],
          ["Natijani bo'rttirish", "Rad javobidan keyin to'xtash"],
          ["Rezyume", "Audit + keys", "Muntazam arizalar"],
          ["Raqobat", "Tajriba talabi"], ["Suhbat", "Portfolio"]),
    ],
    [W(1, "Asoslar", ["Qidiruv qanday ishlaydi", "SEO turlari", "Blog ochish", "Raqiblar", "SEO lug'ati", "Tahlil"]),
     W(2, "Kalit so'zlar", ["Kalit so'z nima", "Tadqiqot vositalari", "Ro'yxat tuzish", "Guruhlash", "Sarlavha yozish", "Birinchi maqola"]),
     W(3, "On-page", ["Meta tavsif", "Sarlavhalar tuzilishi", "Ichki havolalar", "Rasmlar", "Matn sifati", "2-maqola"]),
     W(4, "Texnik", ["Search Console", "Indekslash", "Tezlik", "Mobil versiya", "Audit", "Tuzatish rejasi"])],
    ["Google'ning SEO Starter Guide'ini o'qishni boshlash (bugun, 30 daqiqa)", "Bepul blog ochish (bugun, 20 daqiqa)", "O'z sohangiz bo'yicha 10 ta qidiruv so'zini yozish (bugun, 15 daqiqa)"],
    MENTOR_GENERIC,
    [R("Google — SEO Starter Guide", "https://developers.google.com/search/docs/fundamentals/seo-starter-guide"), R("Google Search Console", "https://search.google.com/search-console/about"), R("Moz — Beginner's Guide to SEO", "https://moz.com/beginners-guide-to-seo")],
    [(1, "Mashq sayti"), (5, "3+ maqola"), (10, "Texnik audit"), (16, "Real loyiha"), (20, "Portfolio va arizalar")],
)

P2["video_motion"] = C(
    "Video va motion kontent mutaxassisi", "content_media", "Kontent va media",
    "Video va motion mutaxassisi kadr, ritm va harakat orqali hikoya qiladi: reklama roliklari, reels, animatsiyalar. Vizual his-tuyg'u va sabr bilan detal ustida ishlashni yoqtiradigan odam uchun.",
    ["Junior videomontajchi / motion dizayner vakansiyalari", "Freelance: reels va reklama roliklari", "Agentlik yoki media kompaniyada stajyorlik"],
    "Motion dizayn, rejissyorlik yoki kontent prodyuserlik",
    [
        S(0, "SETUP", "Tayyorgarlik", 1, "1-2 soat", "Montaj dasturi va birinchi kichik video",
          [("Kamera yo'q", "Telefon kamerasi yetarli"), ("Dastur pullik", "Bepul montaj dasturlari bilan boshlash")],
          ["30 daqiqa: Video turlari", "30 daqiqa: Dastur o'rnatish", "60 daqiqa: 15 soniyalik video"],
          ["Dastur o'rnatildi", "Birinchi video montaj qilindi", "Yoqqan videolar papkasi bor"],
          ["Faqat effektlar bilan o'ynash", "Videoni tugatmaslik"],
          ["Montaj dasturi", "Birinchi video", "Ilhom papkasi"],
          ["Texnika", "Qayerdan boshlash"], ["Montaj asoslari"]),
        S(1, "SHOOTING + EDITING", "Suratga olish va montaj", 4, "2 soat", "Kadr, yorug'lik va montaj asoslari",
          [("Video titraydi", "Ikki qo'l bilan ushlash yoki tripod"), ("Montaj zerikarli", "Musiqa ritmiga moslab kesish")],
          ["30 daqiqa: Kadr va yorug'lik", "60 daqiqa: Montaj", "30 daqiqa: Tahlil"],
          ["Uchdan bir qoidasini qo'llayman", "Ovozni toza yozaman", "Ritmga moslab montaj qilaman"],
          ["Uzun, keraksiz joylarni qoldirish", "Ovozga e'tibor bermaslik"],
          ["5+ qisqa video", "Toza ovoz", "Rang tuzatish asoslari"],
          ["Texnika", "Ritm"], ["Kadr", "Montaj", "Ovoz"]),
        S(2, "MOTION BASICS", "Motion asoslari", 5, "2 soat", "Oddiy animatsiyalar",
          [("Animatsiya qiyin", "Matn va logotip animatsiyasidan boshlash"), ("Kompyuter kuchsiz", "Yengil loyihalar va qisqa formatlar")],
          ["30 daqiqa: Animatsiya tamoyillari", "60 daqiqa: Mashq", "30 daqiqa: Takrorlash"],
          ["Keyframe bilan ishlayman", "Logotipni jonlantirdim", "Silliq harakat qilaman"],
          ["Haddan ko'p effekt", "Tamoyillarsiz ishlash"],
          ["3+ animatsiya", "Logotip animatsiyasi", "Titrlar"],
          ["Sabr", "Detal"], ["Keyframe", "Motion tamoyillari"]),
        S(3, "REAL CLIENT", "Birinchi mijoz", 6, "3 soat", "Real buyurtma va showreel boshlanishi",
          [("Mijoz topish", "Tanish biznes yoki tadbir uchun rolik"), ("Brif yo'q", "Boshida maqsad, davomiylik va uslubni kelishish")],
          ["30 daqiqa: Mijoz bilan aloqa", "60 daqiqa: Ishlab chiqarish", "30 daqiqa: Tuzatish"],
          ["1+ real buyurtma", "Muddatda topshirdim", "Fikr asosida tuzatdim"],
          ["Brifsiz ishlash", "Cheksiz tuzatish"],
          ["1+ real rolik", "Kelishilgan tuzatishlar soni", "Keys"],
          ["Muddat", "Mijoz bilan muloqot"], ["Brif", "Mijoz bilan ishlash"]),
        S(4, "JOB READY", "Ishga tayyorlanish", 4, "3 soat", "Showreel va arizalar",
          [("Showreel uzun", "Eng yaxshi 30–60 soniya"), ("Narx", "Ish vaqtiga qarab hisoblash")],
          ["60 daqiqa: Showreel", "60 daqiqa: Ariza", "60 daqiqa: Networking"],
          ["Showreel tayyor", "Har hafta arizalar", "Ishimni tushuntira olaman"],
          ["Hamma ishni showreelga qo'yish", "Rad javobidan keyin to'xtash"],
          ["Showreel", "Portfolio", "Muntazam arizalar"],
          ["Raqobat", "Narx"], ["Showreel", "Taqdimot"]),
    ],
    [W(1, "Boshlanish", ["Video turlari", "Dastur o'rnatish", "Interfeys", "Kesish", "Musiqa qo'yish", "15 soniyalik video"]),
     W(2, "Kadr", ["Uchdan bir qoidasi", "Yorug'lik", "Ovoz", "Plan turlari", "Hikoya kadrlari", "Qisqa rolik"]),
     W(3, "Montaj", ["Ritm", "O'tishlar", "Rang tuzatish", "Titrlar", "Eksport", "Reels"]),
     W(4, "Motion", ["Keyframe", "Matn animatsiyasi", "Logotip animatsiyasi", "Silliqlik", "Ovoz bilan moslash", "Animatsiya"])],
    ["Bepul montaj dasturini o'rnatish (bugun, 20 daqiqa)", "Telefonda 10 ta qisqa kadr olish (bugun, 20 daqiqa)", "Ulardan 15 soniyalik video yig'ish (bugun, 30 daqiqa)"],
    MENTOR_GENERIC,
    [R("DaVinci Resolve — Training", "https://www.blackmagicdesign.com/products/davinciresolve/training"), R("Adobe After Effects — Help", "https://helpx.adobe.com/after-effects.html"), R("Adobe Premiere Pro — Help", "https://helpx.adobe.com/premiere-pro.html")],
    [(1, "Birinchi video"), (5, "5+ qisqa video"), (10, "3+ animatsiya"), (16, "Real buyurtma"), (20, "Showreel va arizalar")],
)

P2["content_copywriting"] = C(
    "Kontent va kopirayting mutaxassisi", "content_media", "Kontent va media",
    "Kontent va kopirayting mutaxassisi so'z orqali hikoya qiladi va ishontiradi: postlar, reklama matnlari, sayt matnlari, ssenariylar. So'z bilan ishlashni va murakkab narsani sodda tushuntirishni yoqtiradigan odam uchun.",
    ["Junior kopirayter / kontent menejer vakansiyalari", "Freelance: matn buyurtmalari", "Agentlik yoki media kompaniyada stajyorlik"],
    "Kontent strategiya, muharrirlik yoki marketing",
    [
        S(0, "SETUP", "Tayyorgarlik", 1, "1-2 soat", "Yozish odati va namunalar",
          [("Nima yozishni bilmayman", "Har kuni bitta kichik matn"), ("Imlo", "Imlo qoidalari va tekshiruv vositasi")],
          ["30 daqiqa: Kontent turlari", "30 daqiqa: Namunalar yig'ish", "60 daqiqa: Birinchi post"],
          ["Namunalar papkasi bor", "Birinchi post yozildi", "Imlo tekshiruvi odat bo'ldi"],
          ["Faqat o'qish, yozmaslik", "Ko'chirish"],
          ["Namunalar", "Birinchi post", "Yozish jadvali"],
          ["Boshlash", "O'ziga ishonch"], ["Yozish odati"]),
        S(1, "WRITING BASICS", "Yozish asoslari", 4, "2 soat", "Aniq va qisqa yozish",
          [("Matn uzun", "Har jumlani qisqartirish mashqi"), ("Sarlavha zaif", "Har matn uchun 5 ta sarlavha varianti")],
          ["30 daqiqa: Qoida", "60 daqiqa: Yozish", "30 daqiqa: Tahrir"],
          ["Qisqa va aniq yozaman", "Sarlavha variantlari yozaman", "O'z matnimni tahrir qilaman"],
          ["Murakkab so'zlar", "Tahrirsiz chiqarish"],
          ["15+ post", "Sarlavha mashqlari", "Tahrir odati"],
          ["Qisqartirish", "Tahrir"], ["Aniq yozish", "Sarlavha", "Tahrir"]),
        S(2, "COPYWRITING", "Ishontiruvchi matn", 5, "2 soat", "Reklama va sotuv matnlari",
          [("Sotuvchi matn yolg'on bo'lib qoladi", "Faqat haqiqiy foydani aytish"), ("Formula ko'p", "Muammo → Yechim → Natija va AIDA'dan boshlash")],
          ["30 daqiqa: Formula", "60 daqiqa: Matn", "30 daqiqa: Fikr so'rash"],
          ["Mijoz og'rig'idan boshlayman", "Aniq chaqiriq (CTA) yozaman", "Bir matnning 2 variantini solishtiraman"],
          ["Bo'rttirilgan va'dalar", "Hamma uchun yozish"],
          ["10+ reklama matni", "Sayt sahifasi matni", "Ssenariy"],
          ["Ishontirish", "Halollik"], ["Kopirayting", "Ssenariy"]),
        S(3, "REAL CLIENT", "Birinchi mijoz", 6, "3 soat", "Real buyurtma va keys",
          [("Mijoz topish", "Tanish kichik biznes sahifasi yoki sayti"), ("Uslub kelishilmagan", "Boshida brend ovozi va auditoriyani so'rash")],
          ["30 daqiqa: Mijoz bilan aloqa", "60 daqiqa: Yozish", "30 daqiqa: Tuzatish"],
          ["1+ real buyurtma", "Kontent reja tuzdim", "Keys yozdim"],
          ["Brifsiz yozish", "Muddatni buzish"],
          ["1+ real ish", "Kontent reja", "Keys"],
          ["Muddat", "Mijoz bilan muloqot"], ["Kontent reja", "Mijoz bilan ishlash"]),
        S(4, "JOB READY", "Ishga tayyorlanish", 4, "3 soat", "Portfolio va arizalar",
          [("Portfolio tartibsiz", "Turlari bo'yicha 6–8 eng yaxshi matn"), ("Test topshiriq", "Muddatda va brifga mos topshirish")],
          ["60 daqiqa: Portfolio", "60 daqiqa: Ariza", "60 daqiqa: Test topshiriq mashqi"],
          ["Portfolio onlayn", "Har hafta arizalar", "Test topshiriqlarni bajaryapman"],
          ["Hamma matnni qo'yish", "Rad javobidan keyin to'xtash"],
          ["Portfolio", "6–8 namuna", "Muntazam arizalar"],
          ["Raqobat", "Test topshiriqlar"], ["Portfolio", "Taqdimot"]),
    ],
    [W(1, "Boshlanish", ["Kontent turlari", "Namunalar", "Imlo tekshiruvi", "Birinchi post", "Tahrir", "3 ta post"]),
     W(2, "Aniq yozish", ["Qisqa jumla", "Faol nisbat", "Sarlavha", "Kirish", "Tuzilma", "Maqola"]),
     W(3, "Ishontirish", ["Mijoz og'rig'i", "Muammo → Yechim → Natija", "AIDA", "CTA", "2 variant", "Reklama matni"]),
     W(4, "Formatlar", ["Sayt matni", "Ssenariy", "Xabarnoma matni", "Kontent reja", "Brend ovozi", "Mini portfolio"])],
    ["Yoqqan 10 ta post yoki reklamani bitta papkaga yig'ish (bugun, 20 daqiqa)", "O'zingiz yaxshi biladigan mavzuda 1 ta post yozish (bugun, 30 daqiqa)", "Uni ikki baravar qisqartirib, ma'nosini saqlash (bugun, 20 daqiqa)"],
    MENTOR_GENERIC,
    [R("HubSpot Academy", "https://academy.hubspot.com/"), R("Google — Developer documentation style guide", "https://developers.google.com/style"), R("Nielsen Norman Group — Articles", "https://www.nngroup.com/articles/")],
    [(1, "Birinchi post"), (5, "15+ post"), (10, "Reklama matnlari"), (16, "Real buyurtma"), (20, "Portfolio va arizalar")],
)

P2["product_management"] = C(
    "Product menejer", "product_project", "Mahsulot va loyiha boshqaruvi",
    "Product menejer \"nimani va nima uchun qilamiz?\" degan savolga javob beradi: foydalanuvchini tushunadi, g'oyalarni saralaydi, jamoani bir maqsadga yo'naltiradi. Odamlarni tushunishni va qaror qabul qilishni yoqtiradigan odam uchun. Ko'pincha boshqa roldan (analitik, loyiha, dizayn) o'tib kelinadi.",
    ["Junior/Associate Product Manager vakansiyalari", "Product analitik yoki loyiha menejeri orqali kirish", "Portfolio: mahsulot keyslari"],
    "Product menejer, keyinchalik Product lead",
    [
        S(0, "SETUP", "Tayyorgarlik", 1, "1-2 soat", "Product menejer ishini tushunish",
          [("Rol mavhum", "Real ilovalarni tahlil qilishdan boshlash"), ("Tajriba yo'q", "O'z hayotingizdagi kichik loyihalarni misol qilish")],
          ["30 daqiqa: PM nima qiladi", "30 daqiqa: Ilova tahlili", "60 daqiqa: Mahsulot kundaligi"],
          ["PM vazifalarini tushuntira olaman", "3 ta ilovani tahlil qildim", "Mahsulot kundaligini boshladim"],
          ["Faqat kitob o'qish", "Rolni rahbarlik deb tushunish"],
          ["Rol tushunchasi", "3 ta ilova tahlili", "Kundalik"],
          ["Mavhumlik", "Qayerdan boshlash"], ["Mahsulot fikrlash"]),
        S(1, "USER RESEARCH", "Foydalanuvchini tushunish", 4, "2 soat", "Intervyular va muammo ta'rifi",
          [("Noto'g'ri savollar", "O'tmishdagi xatti-harakat haqida so'rash"), ("Odam topish", "Tanishlar va onlayn hamjamiyatlar")],
          ["30 daqiqa: Usul", "60 daqiqa: Intervyu", "30 daqiqa: Xulosa"],
          ["5+ intervyu o'tkazdim", "Muammoni aniq yozaman", "Taxmin va faktni ajrataman"],
          ["\"Yoqadimi?\" deb so'rash", "O'z g'oyasini sotish"],
          ["5+ intervyu", "Muammo ta'rifi", "Foydalanuvchi portreti"],
          ["Tinglash", "Xolislik"], ["Customer interview", "Problem framing"]),
        S(2, "PRIORITIZATION + SPECS", "Saralash va talablar", 5, "2 soat", "Reja va talablar hujjati",
          [("G'oya ko'p", "Qiymat va harakat bo'yicha saralash"), ("Talablar noaniq", "User story va qabul mezonlari")],
          ["30 daqiqa: Freymvork", "60 daqiqa: Hujjat yozish", "30 daqiqa: Fikr so'rash"],
          ["G'oyalarni saralayman", "User story yozaman", "Roadmap tuzaman"],
          ["Hamma narsani birdan qilish", "Hujjatni hech kim o'qimaydigan qilish"],
          ["Saralangan g'oyalar ro'yxati", "Talablar hujjati (PRD)", "Mahsulot roadmapi"],
          ["Ustuvorlik", "Yozish"], ["Prioritization", "User stories", "Roadmap"]),
        S(3, "METRICS + PROJECT", "Ko'rsatkich va loyiha", 6, "3 soat", "Mahsulot keysi",
          [("Ko'rsatkichlar tushunarsiz", "Bitta asosiy ko'rsatkich tanlash"), ("Real mahsulot yo'q", "Mavjud ilova uchun yaxshilash taklifi yoki o'z kichik loyihangiz")],
          ["30 daqiqa: Metrikalar", "60 daqiqa: Keys", "30 daqiqa: Taqdimot"],
          ["Asosiy ko'rsatkichni tanlayman", "Gipotezani tekshiruvga aylantiraman", "Keysni taqdim etdim"],
          ["Ko'rsatkichsiz qaror", "Faqat g'oya, tekshiruvsiz"],
          ["To'liq mahsulot keysi", "Metrikalar", "Taqdimot"],
          ["Analitika", "Oxiriga yetkazish"], ["Product metrics", "Experimentation"]),
        S(4, "JOB READY", "Ishga tayyorlanish", 4, "3 soat", "Ariza va suhbatlar",
          [("Junior PM o'rinlari kam", "Yaqin rol orqali kirish va ichkarida o'tish"), ("Keys-suhbat", "Mahsulot savollarini ovoz chiqarib yechish mashqi")],
          ["60 daqiqa: Keyslar", "60 daqiqa: Ariza", "60 daqiqa: Suhbat mashqi"],
          ["Rezyume tayyor", "Har hafta arizalar", "Keysimni tushuntira olaman"],
          ["Faqat PM o'rinlariga ariza", "Rad javobidan keyin to'xtash"],
          ["Rezyume", "2 ta keys", "Muntazam arizalar"],
          ["Tajriba talabi", "Raqobat"], ["Suhbat", "Keys taqdimoti"]),
    ],
    [W(1, "Rol", ["PM nima qiladi", "Ilova tahlili 1", "Ilova tahlili 2", "Ilova tahlili 3", "Mahsulot kundaligi", "Xulosa"]),
     W(2, "Foydalanuvchi", ["Intervyu usuli", "Savollar ro'yxati", "Intervyu 1", "Intervyu 2", "Intervyu 3", "Muammo ta'rifi"]),
     W(3, "Saralash", ["G'oyalar ro'yxati", "Qiymat/harakat", "User story", "Qabul mezonlari", "Roadmap", "PRD"]),
     W(4, "Ko'rsatkich", ["Metrikalar", "Asosiy ko'rsatkich", "Gipoteza", "Tajriba rejasi", "Keys yozish", "Taqdimot"])],
    ["Eng ko'p ishlatadigan ilovangizni tanlab, unda nima noqulayligini yozish (bugun, 20 daqiqa)", "Bir tanishingizdan oxirgi marta shu ishni qanday qilganini so'rash (bugun, 20 daqiqa)", "Bitta yaxshilash g'oyasini muammo → yechim ko'rinishida yozish (bugun, 20 daqiqa)"],
    MENTOR_GENERIC,
    [R("Atlassian — Product management guide", "https://www.atlassian.com/agile/product-management"), R("SVPG — Articles", "https://www.svpg.com/articles/"), R("ProductPlan — Learning center", "https://www.productplan.com/learn/")],
    [(1, "3 ta ilova tahlili"), (5, "5+ intervyu"), (10, "PRD va roadmap"), (16, "Mahsulot keysi"), (20, "Ariza va suhbatlar")],
)
