from h import S, W, R, C, MENTOR_GENERIC

P3 = {}

P3["project_management"] = C(
    "Loyiha menejeri", "product_project", "Mahsulot va loyiha boshqaruvi",
    "Loyiha menejeri ishni rejalashtiradi, vazifalarni taqsimlaydi va hammasi vaqtida, kelishilgan doirada tugashini kuzatadi. Tartibni, rejani va odamlarni bir maqsadga yig'ishni yoqtiradigan odam uchun.",
    ["Junior loyiha menejeri / koordinator vakansiyalari", "Loyiha yordamchisi sifatida stajyorlik", "Portfolio: tugallangan loyiha hujjatlari"],
    "Loyiha menejeri, keyinchalik dastur (program) menejeri",
    [
        S(0, "SETUP", "Tayyorgarlik", 1, "1-2 soat", "Loyiha boshqaruvi asoslari",
          [("Tajriba yo'q", "Hayotdagi loyihalar: tadbir, ta'mirlash, o'qish rejasi"), ("Vosita tanlash", "Bepul Trello yoki Notion bilan boshlash")],
          ["30 daqiqa: Loyiha nima", "30 daqiqa: Vosita", "60 daqiqa: Kichik loyiha rejasi"],
          ["Loyiha bosqichlarini bilaman", "Vazifalar taxtasini ochdim", "Kichik reja tuzdim"],
          ["Faqat nazariya", "Rejasiz boshlash"],
          ["Loyiha tushunchasi", "Vazifalar taxtasi", "Birinchi reja"],
          ["Mavhumlik", "Tartib"], ["Loyiha asoslari"]),
        S(1, "PLANNING", "Rejalashtirish", 4, "2 soat", "To'liq loyiha rejasi",
          [("Muddatni noto'g'ri baholash", "Vazifani kichik bo'laklarga bo'lish"), ("Bog'liqliklar", "Qaysi vazifa qaysinisini kutishini chizish")],
          ["30 daqiqa: Usul", "60 daqiqa: Reja tuzish", "30 daqiqa: Tekshirish"],
          ["Ish tuzilmasini (WBS) tuzaman", "Gantt jadvali chizaman", "Bog'liqliklarni ko'raman"],
          ["Juda umumiy reja", "Zaxira vaqtsiz reja"],
          ["WBS", "Gantt jadvali", "Muddat baholari"],
          ["Baholash", "Detal"], ["WBS", "Gantt", "Baholash"]),
        S(2, "AGILE + COMMUNICATION", "Agile va muloqot", 5, "2 soat", "Scrum/Kanban va jamoa muloqoti",
          [("Agile atamalari", "Scrum qo'llanmasini o'qib, kichik jamoada sinash"), ("Kelishmovchilik", "Muloqot rejasi va aniq kelishuvlar")],
          ["30 daqiqa: Agile", "60 daqiqa: Amaliyot", "30 daqiqa: Hisobot"],
          ["Sprint rejalashtiraman", "Stand-up o'tkazaman", "Holat hisobotini yozaman"],
          ["Yig'ilishlarni haddan ko'p qilish", "Muammoni yashirish"],
          ["Scrum/Kanban amaliyoti", "Muloqot rejasi", "Haftalik holat hisoboti"],
          ["Odamlar bilan ishlash", "Ochiqlik"], ["Scrum", "Kanban", "Muloqot"]),
        S(3, "RISKS + REAL PROJECT", "Risklar va real loyiha", 6, "3 soat", "Real loyihani boshqarish",
          [("Real loyiha yo'q", "Ko'ngilli tashkilot, tadbir yoki tanishlar jamoasi loyihasi"), ("Kutilmagan muammolar", "Risklar ro'yxati va zaxira rejasi")],
          ["30 daqiqa: Risklar", "60 daqiqa: Loyiha", "30 daqiqa: Hisobot"],
          ["Real loyihani boshqardim", "Risklar ro'yxati bor", "Yakuniy xulosa yozdim"],
          ["Muammoni kech aytish", "Xulosasiz yakunlash"],
          ["Real loyiha", "Risklar ro'yxati", "Yakuniy xulosa (retrospektiva)"],
          ["Mas'uliyat", "Bosim"], ["Risk management", "Stakeholder management"]),
        S(4, "JOB READY", "Ishga tayyorlanish", 4, "3 soat", "Ariza va suhbatlar",
          [("Tajriba kam", "Real loyiha hujjatlarini ko'rsatish"), ("Sertifikat", "Bepul yoki arzon boshlang'ich kurslar — majburiy emas")],
          ["60 daqiqa: Portfolio", "60 daqiqa: Ariza", "60 daqiqa: Suhbat mashqi"],
          ["Rezyume tayyor", "Har hafta arizalar", "Loyiham haqida STAR usulida gapira olaman"],
          ["Umumiy gaplar", "Rad javobidan keyin to'xtash"],
          ["Rezyume", "Loyiha hujjatlari", "Muntazam arizalar"],
          ["Tajriba talabi", "Raqobat"], ["Suhbat", "Portfolio"]),
    ],
    [W(1, "Asoslar", ["Loyiha nima", "Bosqichlar", "Vosita", "Maqsad yozish", "Vazifalar", "Mini reja"]),
     W(2, "Reja", ["WBS", "Baholash", "Bog'liqlik", "Gantt", "Zaxira vaqt", "To'liq reja"]),
     W(3, "Agile", ["Scrum", "Kanban", "Sprint", "Stand-up", "Retrospektiva", "Sprint mashqi"]),
     W(4, "Muloqot", ["Manfaatdor tomonlar", "Muloqot rejasi", "Holat hisoboti", "Risklar", "Yig'ilish o'tkazish", "Hisobot"])],
    ["Bepul vazifalar taxtasini ochish (bugun, 10 daqiqa)", "Yaqin oydagi bir ishingizni (tadbir, ta'mir) loyiha sifatida yozish (bugun, 30 daqiqa)", "Uni 10 ta vazifaga bo'lib, muddat qo'yish (bugun, 20 daqiqa)"],
    MENTOR_GENERIC,
    [R("Atlassian — Project management", "https://www.atlassian.com/agile/project-management"), R("The Scrum Guide", "https://scrumguides.org/"), R("PMI", "https://www.pmi.org/")],
    [(1, "Birinchi reja"), (5, "WBS va Gantt"), (10, "Agile amaliyoti"), (16, "Real loyiha"), (20, "Ariza va suhbatlar")],
)

P3["business_analysis"] = C(
    "Biznes-analitik", "product_project", "Mahsulot va loyiha boshqaruvi",
    "Biznes-analitik jarayonni o'rganib, qayerda vaqt va resurs behuda ketayotganini topadi va yechimni talablar ko'rinishida yozadi. Har narsaning sababini bilmoqchi bo'ladigan, tartibli va diqqatli odam uchun.",
    ["Junior biznes-analitik vakansiyalari", "Stajyorlik yoki operatsion rol orqali kirish", "Portfolio: jarayon tahlili keyslari"],
    "Biznes-analitik, keyinchalik tizim analitigi yoki product",
    [
        S(0, "SETUP", "Tayyorgarlik", 1, "1-2 soat", "Biznes-analitik ishini tushunish",
          [("Rol mavhum", "Kundalik jarayonni (masalan, do'kondan xarid) qadamlarga bo'lib yozish"), ("Vosita", "Bepul diagramma vositasi")],
          ["30 daqiqa: BA nima qiladi", "30 daqiqa: Vosita", "60 daqiqa: Jarayonni yozish"],
          ["BA vazifalarini tushuntira olaman", "Bir jarayonni qadamlarga bo'ldim", "Diagramma vositasini ochdim"],
          ["Faqat nazariya", "Rolni dasturchi bilan adashtirish"],
          ["Rol tushunchasi", "Birinchi jarayon tavsifi", "Vosita"],
          ["Mavhumlik", "Atamalar"], ["Analitik fikrlash"]),
        S(1, "PROCESS MODELING", "Jarayonni chizish", 4, "2 soat", "Jarayon diagrammalari",
          [("BPMN belgilari ko'p", "Avval 5 ta asosiy belgi"), ("Jarayon chalkash", "\"Hozir qanday\" va \"qanday bo'lishi kerak\"ni alohida chizish")],
          ["30 daqiqa: BPMN", "60 daqiqa: Diagramma", "30 daqiqa: Tahlil"],
          ["BPMN diagramma chizaman", "Muammoli qadamni topaman", "\"Hozir\" va \"keyin\" variantini chizaman"],
          ["Juda detal yoki juda umumiy diagramma", "Muammoni sababsiz yozish"],
          ["3+ jarayon diagrammasi", "As-is / to-be", "Muammolar ro'yxati"],
          ["Detal darajasi", "Mantiq"], ["BPMN", "Process analysis"]),
        S(2, "REQUIREMENTS", "Talablar", 5, "2 soat", "Talablar hujjati",
          [("Talab noaniq", "Har talabni tekshirsa bo'ladigan qilib yozish"), ("Manfaatdorlar ko'p", "Intervyu va kelishuv bayonnomasi")],
          ["30 daqiqa: Usul", "60 daqiqa: Yozish", "30 daqiqa: Tekshirish"],
          ["Funksional va nofunksional talablarni ajrataman", "User story va use case yozaman", "Intervyu o'tkazaman"],
          ["\"Qulay bo'lsin\" kabi noaniq talab", "Kelishuvsiz hujjat"],
          ["Talablar hujjati", "Use case'lar", "Intervyu yozuvlari"],
          ["Aniqlik", "Muloqot"], ["Requirements", "Use cases", "Interviewing"]),
        S(3, "DATA + CASE", "Ma'lumot va keys", 6, "3 soat", "Dalilga asoslangan keys",
          [("Raqamlar bilan ishlash", "Excel va SQL asoslari"), ("Real keys yo'q", "Tanish biznes jarayoni yoki ochiq ma'lumot")],
          ["30 daqiqa: Excel/SQL", "60 daqiqa: Keys", "30 daqiqa: Taqdimot"],
          ["Ma'lumot bilan muammoni isbotlayman", "Yechim taklifini hisob bilan asoslayman", "Keysni taqdim etdim"],
          ["Dalilsiz xulosa", "Faqat diagramma, raqamsiz"],
          ["To'liq keys", "Excel/SQL tahlil", "Taqdimot"],
          ["Ma'lumot", "Taqdimot"], ["Excel", "SQL asoslari", "Taqdimot"]),
        S(4, "JOB READY", "Ishga tayyorlanish", 4, "3 soat", "Ariza va suhbatlar",
          [("Tajriba kam", "Keyslarni hujjatlari bilan ko'rsatish"), ("Keys-suhbat", "Jarayon muammosini ovoz chiqarib tahlil qilish mashqi")],
          ["60 daqiqa: Portfolio", "60 daqiqa: Ariza", "60 daqiqa: Suhbat mashqi"],
          ["Rezyume tayyor", "Har hafta arizalar", "Keysimni tushuntira olaman"],
          ["Faqat nazariy bilim", "Rad javobidan keyin to'xtash"],
          ["Rezyume", "2 ta keys", "Muntazam arizalar"],
          ["Tajriba talabi", "Raqobat"], ["Suhbat", "Portfolio"]),
    ],
    [W(1, "Asoslar", ["BA nima", "Jarayon nima", "Vosita", "Jarayonni yozish", "Muammo topish", "Xulosa"]),
     W(2, "BPMN", ["Asosiy belgilar", "As-is", "To-be", "Muammoli qadam", "Diagramma tahlili", "3 ta diagramma"]),
     W(3, "Talablar", ["Talab turlari", "User story", "Use case", "Intervyu", "Kelishuv", "Talablar hujjati"]),
     W(4, "Ma'lumot", ["Excel asoslari", "Pivot jadval", "SQL SELECT", "Hisob-kitob", "Keys yozish", "Taqdimot"])],
    ["Kundalik bitta jarayonni (masalan, kafeda buyurtma) qadamlarga bo'lib yozish (bugun, 20 daqiqa)", "Unda vaqt behuda ketadigan joyni belgilash (bugun, 15 daqiqa)", "Bepul diagramma vositasida chizish (bugun, 30 daqiqa)"],
    MENTOR_GENERIC,
    [R("IIBA", "https://www.iiba.org/"), R("Lucidchart — BPMN tutorial", "https://www.lucidchart.com/pages/bpmn"), R("SQLBolt", "https://sqlbolt.com/")],
    [(1, "Birinchi jarayon tavsifi"), (5, "3+ diagramma"), (10, "Talablar hujjati"), (16, "Dalilga asoslangan keys"), (20, "Ariza va suhbatlar")],
)

P3["sales_manager"] = C(
    "Sotuv menejeri", "business_sales", "Sotuv va mijozlar bilan ishlash",
    "Sotuv menejeri mijozning ehtiyojini tushunib, unga mos yechimni taklif qiladi va kelishuvga olib boradi. Odamlar bilan gaplashishni, maqsad qo'yib unga erishishni yoqtiradigan odam uchun.",
    ["Junior sotuv menejeri vakansiyalari", "IT yoki xizmat kompaniyasida sotuv stajyorligi", "Freelance: kichik biznes uchun mijoz topish"],
    "Katta mijozlar menejeri (B2B), sotuv rahbari yoki Customer Success",
    [
        S(0, "SETUP", "Tayyorgarlik", 1, "1-2 soat", "Sotuv jarayonini tushunish",
          [("Sotuv \"aldash\" degan fikr", "Yaxshi sotuv — ehtiyojni tushunib, foydali yechim berish"), ("Tajriba yo'q", "Kundalik muzokaralarni kuzatish")],
          ["30 daqiqa: Sotuv bosqichlari", "30 daqiqa: Mahsulot tanlash", "60 daqiqa: Sotuvchilarni kuzatish"],
          ["Sotuv bosqichlarini bilaman", "Mashq uchun mahsulot tanladim", "3 ta sotuv suhbatini kuzatdim"],
          ["Faqat motivatsion video", "Bosim bilan sotish"],
          ["Sotuv bosqichlari", "Mashq mahsuloti", "Kuzatuv yozuvlari"],
          ["Qo'rquv", "Noto'g'ri tasavvur"], ["Sotuv asoslari"]),
        S(1, "NEEDS + PITCH", "Ehtiyoj va taqdimot", 4, "2 soat", "Savol berish va taqdimot",
          [("Ko'p gapirish", "Savol berib, ko'proq tinglash"), ("Taqdimot uzun", "Foyda bilan boshlanadigan 1 daqiqalik taqdimot")],
          ["30 daqiqa: Usul", "60 daqiqa: Rol o'yini", "30 daqiqa: Tahlil"],
          ["Ochiq savollar beraman", "1 daqiqalik taqdimot tayyor", "Rol o'yinida mashq qildim"],
          ["Mijozni bo'lish", "Faqat narx haqida gapirish"],
          ["Savollar ro'yxati", "Taqdimot", "5+ rol o'yini"],
          ["Tinglash", "Ishonch"], ["Ehtiyojni aniqlash", "Taqdimot"]),
        S(2, "OBJECTIONS + CRM", "E'tirozlar va CRM", 5, "2 soat", "E'tirozlar bilan ishlash va CRM",
          [("\"Qimmat\" degan javob", "Qiymatni tushuntirish va variantlar"), ("Mijozlarni unutish", "CRM'da har bir aloqani yozish")],
          ["30 daqiqa: E'tirozlar", "60 daqiqa: CRM mashqi", "30 daqiqa: Rol o'yini"],
          ["Asosiy e'tirozlarga javobim bor", "CRM'da voronka yuritaman", "Keyingi qadamni doim kelishaman"],
          ["E'tirozdan keyin taslim bo'lish", "Yozuvsiz ishlash"],
          ["E'tirozlar jadvali", "CRM voronka", "Keyingi qadam odati"],
          ["Rad javobi", "Tartib"], ["Objection handling", "CRM"]),
        S(3, "REAL SALES", "Real sotuv", 6, "3 soat", "Real mijozlar bilan ishlash",
          [("Mijoz topish", "Tanish kichik biznes mahsuloti yoki xizmati"), ("Ko'p rad javobi", "Har rad javobidan keyin qisqa tahlil")],
          ["60 daqiqa: Mijoz qidirish va qo'ng'iroq", "30 daqiqa: CRM", "30 daqiqa: Tahlil"],
          ["Real mijozlar bilan gaplashdim", "Kelishuvga olib bordim", "Natijalarni CRM'da yozdim"],
          ["Va'dani bo'rttirish", "Kuzatuvsiz qoldirish"],
          ["Real sotuv tajribasi", "CRM tarixi", "O'z xulosalarim"],
          ["Rad javobi", "Bosim"], ["Prospecting", "Closing"]),
        S(4, "JOB READY", "Ishga tayyorlanish", 4, "3 soat", "Ariza va suhbatlar",
          [("Tajriba kam", "Real sotuv tajribasi va CRM yozuvlari"), ("Suhbatda sotish topshirig'i", "\"Menga shu ruchkani soting\" mashqi")],
          ["60 daqiqa: Rezyume", "60 daqiqa: Ariza", "60 daqiqa: Suhbat mashqi"],
          ["Rezyume tayyor", "Har hafta arizalar", "Sotuv mashqini bajara olaman"],
          ["Faqat \"men gapga ustaman\" deyish", "Rad javobidan keyin to'xtash"],
          ["Rezyume", "Sotuv tajribasi tavsifi", "Muntazam arizalar"],
          ["Raqobat", "Rad javoblari"], ["Suhbat", "O'zini taqdim etish"]),
    ],
    [W(1, "Asoslar", ["Sotuv bosqichlari", "Yaxshi va yomon sotuv", "Mahsulot tanlash", "Kuzatuv", "Mijoz portreti", "Xulosa"]),
     W(2, "Savollar", ["Ochiq savollar", "Faol tinglash", "Ehtiyojni aniqlash", "Rol o'yini", "Rol o'yini", "Tahlil"]),
     W(3, "Taqdimot", ["Foyda va xususiyat", "1 daqiqalik taqdimot", "Hikoya", "Rol o'yini", "Fikr so'rash", "Taqdimot tayyor"]),
     W(4, "E'tirozlar", ["E'tiroz turlari", "\"Qimmat\"", "\"O'ylab ko'raman\"", "CRM", "Keyingi qadam", "E'tirozlar jadvali"])],
    ["Mashq uchun bitta mahsulot yoki xizmat tanlash (bugun, 10 daqiqa)", "Uni sotib olishi mumkin bo'lgan odamga 5 ta ochiq savol yozish (bugun, 20 daqiqa)", "1 daqiqalik taqdimotni ovoz chiqarib mashq qilish (bugun, 20 daqiqa)"],
    MENTOR_GENERIC,
    [R("HubSpot Academy", "https://academy.hubspot.com/"), R("Salesforce Trailhead", "https://trailhead.salesforce.com/"), R("HubSpot — Sales blog", "https://blog.hubspot.com/sales")],
    [(1, "Sotuv bosqichlari"), (5, "Taqdimot va savollar"), (10, "E'tirozlar va CRM"), (16, "Real sotuv tajribasi"), (20, "Ariza va suhbatlar")],
)

P3["customer_success"] = C(
    "Customer Success mutaxassisi", "business_sales", "Sotuv va mijozlar bilan ishlash",
    "Customer Success mutaxassisi mijoz mahsulotdan to'liq foyda olishiga yordam beradi va uni uzoq muddat saqlab qoladi. G'amxo'r, sabrli, muammoni oxirigacha hal qilishni yoqtiradigan odam uchun.",
    ["Mijozlarni qo'llab-quvvatlash / Customer Success vakansiyalari", "IT kompaniyada support orqali kirish", "Portfolio: qo'llanma va jarayon namunalari"],
    "Customer Success menejer, keyinchalik CS rahbari yoki Account menejer",
    [
        S(0, "SETUP", "Tayyorgarlik", 1, "1-2 soat", "Customer Success ishini tushunish",
          [("Support bilan farqi", "Support — savolga javob, CS — mijoz natijasiga erishishi"), ("Tajriba yo'q", "Yaxshi va yomon xizmat misollarini yig'ish")],
          ["30 daqiqa: CS nima", "30 daqiqa: Xizmat misollari", "60 daqiqa: Mahsulot tanlash"],
          ["CS va support farqini bilaman", "Xizmat misollari bor", "Mashq mahsuloti tanlandi"],
          ["Faqat nazariya", "Rolni oddiy operator deb tushunish"],
          ["Rol tushunchasi", "Misollar", "Mashq mahsuloti"],
          ["Mavhumlik", "Qayerdan boshlash"], ["Mijozga yo'naltirilgan fikrlash"]),
        S(1, "COMMUNICATION", "Muloqot", 4, "2 soat", "Yozma va og'zaki muloqot",
          [("Jahli chiqqan mijoz", "Uzr, aniq keyingi qadam va muddat"), ("Javob uzun", "Qisqa, aniq va do'stona shablonlar")],
          ["30 daqiqa: Usul", "60 daqiqa: Javob yozish mashqi", "30 daqiqa: Rol o'yini"],
          ["Faol tinglayman", "Qisqa va aniq javob yozaman", "Qiyin mijoz bilan mashq qildim"],
          ["Mijozni ayblash", "Aniq muddatsiz va'da"],
          ["20+ javob namunasi", "Javob shablonlari", "Rol o'yinlari"],
          ["Sabr", "Hissiyot"], ["Faol tinglash", "Yozma muloqot"]),
        S(2, "ONBOARDING + TOOLS", "Mijozni o'rgatish va vositalar", 5, "2 soat", "Onboarding jarayoni va helpdesk",
          [("Mijoz mahsulotni tushunmaydi", "Qadamma-qadam qo'llanma va qisqa video"), ("Murojaatlar tartibsiz", "Helpdesk yoki CRM'da yozib borish")],
          ["30 daqiqa: Onboarding", "60 daqiqa: Qo'llanma yozish", "30 daqiqa: Vosita"],
          ["Onboarding rejasi tuzaman", "Qo'llanma yozaman", "Helpdesk'da ishlayman"],
          ["Hamma narsani bir kunda o'rgatish", "Yozuvsiz ishlash"],
          ["Onboarding rejasi", "Mahsulot qo'llanmasi", "FAQ"],
          ["Tushuntirish", "Tartib"], ["Onboarding", "Helpdesk/CRM"]),
        S(3, "RETENTION + PRACTICE", "Mijozni saqlash va amaliyot", 6, "3 soat", "Real mijozlar bilan ishlash",
          [("Mijoz ketib qoladi", "Faollik pasayishini erta ko'rish va aloqaga chiqish"), ("Real tajriba yo'q", "Tanish biznesning mijozlar bilan ishlashiga yordam")],
          ["60 daqiqa: Mijozlar bilan aloqa", "30 daqiqa: Ko'rsatkichlar", "30 daqiqa: Takliflar"],
          ["Xavf belgilarini ko'raman", "Mijoz fikrini yig'aman", "Jamoaga yaxshilash taklifi berdim"],
          ["Faqat shikoyat kutish", "Fikrni jamoaga yetkazmaslik"],
          ["Real amaliyot", "Mijoz fikrlari to'plami", "Yaxshilash takliflari"],
          ["Bosim", "Ko'p vazifa"], ["Retention", "Feedback"]),
        S(4, "JOB READY", "Ishga tayyorlanish", 4, "3 soat", "Ariza va suhbatlar",
          [("Tajriba kam", "Qo'llanma va javob namunalarini ko'rsatish"), ("Suhbatda ssenariy", "Jahli chiqqan mijoz ssenariysini mashq qilish")],
          ["60 daqiqa: Portfolio", "60 daqiqa: Ariza", "60 daqiqa: Suhbat mashqi"],
          ["Rezyume tayyor", "Har hafta arizalar", "Ssenariyni yechib bera olaman"],
          ["Umumiy gaplar", "Rad javobidan keyin to'xtash"],
          ["Rezyume", "Namunalar to'plami", "Muntazam arizalar"],
          ["Raqobat", "Tajriba talabi"], ["Suhbat", "Portfolio"]),
    ],
    [W(1, "Asoslar", ["CS nima", "Support bilan farqi", "Xizmat misollari", "Mahsulot tanlash", "Mijoz safari", "Xulosa"]),
     W(2, "Muloqot", ["Faol tinglash", "Yozma javob", "Uzr va keyingi qadam", "Qiyin mijoz", "Shablonlar", "Rol o'yini"]),
     W(3, "Onboarding", ["Onboarding nima", "Reja", "Qo'llanma", "FAQ", "Qisqa video", "Onboarding paketi"]),
     W(4, "Saqlash", ["Xavf belgilari", "Faollik", "Fikr yig'ish", "Taklif yozish", "Helpdesk", "Hisobot"])],
    ["Eng yaxshi va eng yomon xizmat tajribangizni yozish (bugun, 15 daqiqa)", "Jahli chiqqan mijozga javob namunasini yozish (bugun, 20 daqiqa)", "Bir ilova uchun 5 qadamli qo'llanma yozish (bugun, 30 daqiqa)"],
    MENTOR_GENERIC,
    [R("HubSpot Academy", "https://academy.hubspot.com/"), R("Salesforce Trailhead", "https://trailhead.salesforce.com/"), R("Zendesk — Blog", "https://www.zendesk.com/blog/")],
    [(1, "Rol tushunchasi"), (5, "Javob namunalari"), (10, "Onboarding paketi"), (16, "Real amaliyot"), (20, "Ariza va suhbatlar")],
)

P3["accountant"] = C(
    "Buxgalter", "finance_office", "Moliya va raqamli ofis",
    "Buxgalter kompaniya pulining qayerdan kelib, qayerga ketganini aniq hisobga oladi va hisobotlarni qonunga muvofiq tayyorlaydi. Aniqlikni, tartibni va mas'uliyatni yoqtiradigan odam uchun. Qonun va soliq qoidalari o'zgarib turadi — doimiy o'qish talab qilinadi.",
    ["Buxgalter yordamchisi vakansiyalari", "Kichik biznesga birlamchi hujjatlar bo'yicha yordam", "Buxgalteriya firmasida stajyorlik"],
    "Buxgalter, keyinchalik bosh buxgalter yoki moliyaviy tahlilchi",
    [
        S(0, "SETUP", "Tayyorgarlik", 1, "1-2 soat", "Buxgalteriya asoslari bilan tanishuv",
          [("Atamalar ko'p", "Asosiy atamalar lug'ati"), ("Qonunlar murakkab", "Rasmiy manbalardan (soliq.uz, lex.uz) o'qish odati")],
          ["30 daqiqa: Buxgalteriya nima", "30 daqiqa: Rasmiy manbalar", "60 daqiqa: Kirim-chiqim mashqi"],
          ["Asosiy atamalarni bilaman", "Rasmiy manbalarni topa olaman", "Shaxsiy kirim-chiqim jadvali bor"],
          ["Ijtimoiy tarmoqdagi tekshirilmagan maslahatga tayanish", "Faqat nazariya"],
          ["Atamalar lug'ati", "Rasmiy manbalar ro'yxati", "Kirim-chiqim jadvali"],
          ["Atamalar", "Qonunlar"], ["Buxgalteriya asoslari"]),
        S(1, "ACCOUNTING BASICS", "Hisob asoslari", 5, "2 soat", "Ikki yoqlama yozuv va hisoblar",
          [("Debet/kredit tushunarsiz", "Har operatsiyani ikki tomonlama yozish mashqi"), ("Mashq yetmaydi", "Har kuni 5 ta operatsiya")],
          ["45 daqiqa: Nazariya", "45 daqiqa: Operatsiyalar mashqi", "30 daqiqa: Takrorlash"],
          ["Ikki yoqlama yozuvni qo'llayman", "Hisoblar rejasini tushunaman", "Oddiy balans tuzaman"],
          ["Yodlash, tushunmasdan", "Xatoni tekshirmaslik"],
          ["Operatsiyalar jurnali", "Oddiy balans", "Moliyaviy natija hisoboti"],
          ["Mantiq", "Aniqlik"], ["Ikki yoqlama yozuv", "Balans"]),
        S(2, "TAX + DOCUMENTS", "Soliq va hujjatlar", 5, "2 soat", "Birlamchi hujjatlar va soliq asoslari",
          [("Soliq turlari ko'p", "Avval kichik biznes uchun asosiy soliqlar"), ("Hujjatlar", "Elektron hisob-faktura va dalolatnoma namunalari")],
          ["45 daqiqa: Soliq asoslari", "45 daqiqa: Hujjatlar mashqi", "30 daqiqa: Yangiliklar"],
          ["Asosiy soliq turlarini bilaman", "Birlamchi hujjatlarni to'g'ri to'ldiraman", "O'zgarishlarni rasmiy manbadan kuzataman"],
          ["Eskirgan ma'lumotga tayanish", "Hujjatsiz yozuv"],
          ["Soliq asoslari konspekti", "Hujjat namunalari", "Yangiliklarni kuzatish odati"],
          ["Qoidalar o'zgarishi", "Detal"], ["Soliq asoslari", "Birlamchi hujjatlar"]),
        S(3, "SOFTWARE + PRACTICE", "Dastur va amaliyot", 6, "3 soat", "Buxgalteriya dasturi va real amaliyot",
          [("Dastur notanish", "1C yoki boshqa buxgalteriya dasturining o'quv versiyasi"), ("Real tajriba yo'q", "Tanish kichik biznes hujjatlarini tartibga solishga yordam")],
          ["60 daqiqa: Dastur", "30 daqiqa: Excel", "30 daqiqa: Amaliyot"],
          ["Dasturda operatsiya kiritaman", "Excel'da solishtirma qilaman", "Real hujjatlar bilan ishladim"],
          ["Tekshiruvsiz kiritish", "Maxfiy ma'lumotni ehtiyotsiz saqlash"],
          ["Dasturda mashq davri", "Solishtirma hisobot", "Real amaliyot"],
          ["Mas'uliyat", "Maxfiylik"], ["Buxgalteriya dasturi", "Excel"]),
        S(4, "JOB READY", "Ishga tayyorlanish", 4, "3 soat", "Ariza va suhbatlar",
          [("Tajriba talabi", "Yordamchi lavozim va amaliyot orqali kirish"), ("Suhbatda amaliy topshiriq", "Operatsiyalarni yozish mashqi")],
          ["60 daqiqa: Rezyume", "60 daqiqa: Ariza", "60 daqiqa: Suhbat mashqi"],
          ["Rezyume tayyor", "Har hafta arizalar", "Amaliy topshiriqni bajara olaman"],
          ["Faqat bosh buxgalter o'rinlariga ariza", "Rad javobidan keyin to'xtash"],
          ["Rezyume", "Amaliyot tavsifi", "Muntazam arizalar"],
          ["Tajriba talabi", "Raqobat"], ["Suhbat", "Rezyume"]),
    ],
    [W(1, "Asoslar", ["Buxgalteriya nima", "Atamalar", "Rasmiy manbalar", "Kirim-chiqim", "Hujjat turlari", "Mashq"]),
     W(2, "Hisoblar", ["Aktiv va passiv", "Debet va kredit", "Hisoblar rejasi", "Operatsiyalar", "Operatsiyalar", "Jurnal"]),
     W(3, "Hisobotlar", ["Balans", "Moliyaviy natija", "Xatolarni topish", "Solishtirish", "Excel jadval", "Mini hisobot"]),
     W(4, "Soliq va hujjat", ["Soliq turlari", "Hisob-faktura", "Dalolatnoma", "Muddatlar", "Yangiliklar", "Konspekt"])],
    ["Bir oylik shaxsiy kirim-chiqimingizni jadvalga yozishni boshlash (bugun, 20 daqiqa)", "soliq.uz saytida kichik biznes bo'limini ko'rib chiqish (bugun, 20 daqiqa)", "10 ta asosiy atama lug'atini tuzish (bugun, 20 daqiqa)"],
    MENTOR_GENERIC,
    [R("Soliq qo'mitasi", "https://soliq.uz/", "UZ"), R("Lex.uz — qonunchilik", "https://lex.uz/", "UZ"), R("IFRS Foundation", "https://www.ifrs.org/")],
    [(1, "Atamalar va manbalar"), (6, "Ikki yoqlama yozuv"), (11, "Soliq va hujjatlar"), (17, "Dastur va amaliyot"), (21, "Ariza va suhbatlar")],
)

P3["fintech_specialist"] = C(
    "Fintech mutaxassisi", "finance_office", "Moliya va raqamli ofis",
    "Fintech mutaxassisi bank va to'lov xizmatlarining raqamli ishlashiga yordam beradi: to'lov jarayonlari, ilova ichidagi moliyaviy mahsulotlar, operatsiyalar tahlili. Pul va texnologiya kesishmasini yoqtiradigan odam uchun. Bu keng soha — odatda operatsion, analitik yoki mahsulot roli orqali kiriladi.",
    ["Bank/to'lov kompaniyasida operatsion yoki analitik stajyorlik", "Fintech mahsulot jamoasida junior rol", "Portfolio: to'lov jarayoni tahlili"],
    "Fintech product, risk/antifrod yoki to'lov operatsiyalari",
    [
        S(0, "SETUP", "Tayyorgarlik", 1, "1-2 soat", "Fintech sohasini tushunish",
          [("Soha keng", "Avval to'lovlar va raqamli bank bilan boshlash"), ("Atamalar", "Moliya va to'lov lug'ati")],
          ["30 daqiqa: Fintech nima", "30 daqiqa: Ilovalar tahlili", "60 daqiqa: Lug'at"],
          ["Fintech yo'nalishlarini bilaman", "3 ta moliya ilovasini tahlil qildim", "Lug'at bor"],
          ["Faqat kripto haqidagi postlar", "Investitsiya maslahatlarini fakt deb qabul qilish"],
          ["Soha xaritasi", "Ilovalar tahlili", "Lug'at"],
          ["Kenglik", "Atamalar"], ["Fintech asoslari"]),
        S(1, "PAYMENTS + BANKING", "To'lovlar va bank", 4, "2 soat", "To'lov qanday o'tishini tushunish",
          [("Jarayon ko'rinmaydi", "Bitta karta to'lovini qadamma-qadam chizish"), ("Qoidalar", "Markaziy bank va rasmiy manbalar")],
          ["45 daqiqa: Nazariya", "45 daqiqa: Jarayon chizish", "30 daqiqa: Takrorlash"],
          ["Karta to'lovi qadamlarini tushuntira olaman", "Komissiya va foizni hisoblayman", "Asosiy tartibga solish tamoyillarini bilaman"],
          ["Faqat ilova interfeysiga qarash", "Xavfsizlikni e'tiborsiz qoldirish"],
          ["To'lov jarayoni diagrammasi", "Hisob-kitob mashqlari", "Tartibga solish konspekti"],
          ["Mavhum jarayon", "Qoidalar"], ["To'lov tizimlari", "Moliyaviy hisob"]),
        S(2, "DATA + RISK", "Ma'lumot va risk", 5, "2 soat", "Operatsiyalar tahlili va firibgarlik belgilari",
          [("Raqamlar ko'p", "Excel va SQL asoslari"), ("Firibgarlik mavzusi", "Shubhali operatsiya belgilarini o'rganish")],
          ["30 daqiqa: Excel/SQL", "60 daqiqa: Tahlil mashqi", "30 daqiqa: Risk"],
          ["Operatsiyalar jadvalini tahlil qilaman", "Shubhali belgini topaman", "Xulosa yozaman"],
          ["Dalilsiz xulosa", "Shaxsiy ma'lumotni ehtiyotsiz ishlatish"],
          ["Operatsiyalar tahlili", "Risk belgilari ro'yxati", "Xulosa hisoboti"],
          ["Ma'lumot", "Maxfiylik"], ["Excel", "SQL asoslari", "Risk asoslari"]),
        S(3, "PRODUCT CASE", "Mahsulot keysi", 6, "3 soat", "Fintech mahsulot yoki jarayon keysi",
          [("Real ma'lumot yo'q", "Ochiq ma'lumot yoki o'z tajribangiz asosida keys"), ("G'oya keng", "Bitta muammo: masalan, to'lovdagi qadamlarni qisqartirish")],
          ["30 daqiqa: Muammo", "60 daqiqa: Keys", "30 daqiqa: Taqdimot"],
          ["Muammoni foydalanuvchi bilan tekshirdim", "Yechimni risk bilan birga taklif qildim", "Keysni taqdim etdim"],
          ["Risksiz yechim", "Tekshirilmagan raqamlar"],
          ["Mahsulot/jarayon keysi", "Foydalanuvchi fikrlari", "Taqdimot"],
          ["Murakkablik", "Taqdimot"], ["Product thinking", "Taqdimot"]),
        S(4, "JOB READY", "Ishga tayyorlanish", 4, "3 soat", "Ariza va suhbatlar",
          [("Tajriba talabi", "Operatsion yoki stajyorlik rollari orqali kirish"), ("Suhbat", "To'lov jarayonini tushuntirish mashqi")],
          ["60 daqiqa: Portfolio", "60 daqiqa: Ariza", "60 daqiqa: Suhbat mashqi"],
          ["Rezyume tayyor", "Har hafta arizalar", "Keysimni tushuntira olaman"],
          ["Faqat \"fintech product manager\" o'rinlariga ariza", "Rad javobidan keyin to'xtash"],
          ["Rezyume", "Keys", "Muntazam arizalar"],
          ["Tajriba talabi", "Raqobat"], ["Suhbat", "Portfolio"]),
    ],
    [W(1, "Soha", ["Fintech nima", "Yo'nalishlar", "Ilova tahlili 1", "Ilova tahlili 2", "Lug'at", "Xulosa"]),
     W(2, "To'lovlar", ["Karta to'lovi", "O'tkazmalar", "Komissiya", "Xavfsizlik", "Tartibga solish", "Diagramma"]),
     W(3, "Ma'lumot", ["Excel asoslari", "Filtr va jadval", "SQL SELECT", "Guruhlash", "Shubhali belgilar", "Mini tahlil"]),
     W(4, "Keys", ["Muammo tanlash", "Foydalanuvchi bilan suhbat", "Yechim", "Risklar", "Taqdimot", "Keys"])],
    ["Ishlatadigan to'lov ilovangizda bitta o'tkazmani qadamma-qadam yozish (bugun, 20 daqiqa)", "Markaziy bank saytida to'lov tizimlari bo'limini ko'rib chiqish (bugun, 20 daqiqa)", "15 ta moliya atamasi lug'atini tuzish (bugun, 20 daqiqa)"],
    MENTOR_GENERIC,
    [R("O'zbekiston Markaziy banki", "https://cbu.uz/", "UZ"), R("Stripe — Docs", "https://docs.stripe.com/"), R("Investopedia", "https://www.investopedia.com/")],
    [(1, "Soha xaritasi"), (5, "To'lov jarayoni"), (10, "Operatsiyalar tahlili"), (16, "Mahsulot keysi"), (20, "Ariza va suhbatlar")],
)

P3["spreadsheet_specialist"] = C(
    "Excel va Google Sheets mutaxassisi", "finance_office", "Moliya va raqamli ofis",
    "Excel va Google Sheets mutaxassisi qo'lda qilinadigan hisob-kitobni avtomatik jadval va hisobotga aylantiradi. Vaqtni tejashni, tartibni va raqamlar bilan ishlashni yoqtiradigan odam uchun. Bu ko'nikma ko'p ofis lavozimlarida (operator, ofis menejeri, analitik yordamchisi) asos bo'ladi.",
    ["Ofis/operatsion lavozimlar (hisobot, ma'lumot kiritish va tahlil)", "Freelance: kichik biznes uchun jadval va hisobotlar", "Analitik yordamchisi"],
    "Data analitik, moliyaviy tahlilchi yoki operatsion menejer",
    [
        S(0, "SETUP", "Tayyorgarlik", 1, "1-2 soat", "Jadval interfeysi bilan tanishuv",
          [("Excel yo'q", "Google Sheets bepul"), ("Qayerdan boshlash", "O'z kundalik ma'lumotingizdan jadval")],
          ["30 daqiqa: Interfeys", "30 daqiqa: Katakchalar va formatlash", "60 daqiqa: Birinchi jadval"],
          ["Jadval yaratdim", "Formatlashni bilaman", "Oddiy hisob qildim"],
          ["Faqat video ko'rish", "Ma'lumotni tartibsiz kiritish"],
          ["Interfeys", "Birinchi jadval", "Formatlash"],
          ["Interfeys", "Odat"], ["Jadval asoslari"]),
        S(1, "FORMULAS", "Formulalar", 4, "2 soat", "Asosiy formulalar",
          [("Formulalar ko'p", "Avval 10 ta eng kerakli formula"), ("Xato chiqadi", "Xato turlarini o'qishni o'rganish")],
          ["30 daqiqa: Yangi formula", "60 daqiqa: Mashq", "30 daqiqa: Takrorlash"],
          ["SUM, IF, COUNTIF ishlataman", "XLOOKUP/VLOOKUP bilan ma'lumot topaman", "Nisbiy va mutlaq havolani farqlayman"],
          ["Hisobni qo'lda yozish", "Formulani tekshirmaslik"],
          ["10 ta asosiy formula", "Qidiruv formulalari", "Xato turlari"],
          ["Mantiq", "Aniqlik"], ["Formulalar", "Lookup"]),
        S(2, "DATA + PIVOT", "Ma'lumot va pivot", 5, "2 soat", "Tozalangan ma'lumot va pivot hisobotlar",
          [("Ma'lumot tartibsiz", "Tozalash qadamlari: takror, bo'sh, format"), ("Hisobot qo'lda", "Pivot jadval")],
          ["30 daqiqa: Tozalash", "60 daqiqa: Pivot", "30 daqiqa: Grafik"],
          ["Ma'lumotni tozalayman", "Pivot jadval tuzaman", "Tushunarli grafik chizaman"],
          ["Asl ma'lumotni buzish", "Ortiqcha bezakli grafik"],
          ["Tozalash jarayoni", "Pivot hisobot", "3+ grafik"],
          ["Tartib", "Tanlov"], ["Data cleaning", "Pivot", "Grafiklar"]),
        S(3, "AUTOMATION + DASHBOARD", "Avtomatlashtirish va dashboard", 6, "3 soat", "Avtomatik hisobot va dashboard",
          [("Takroriy ish", "Makros yoki Apps Script bilan oddiy avtomatlashtirish"), ("Real vazifa yo'q", "Tanish biznesning hisobi")],
          ["30 daqiqa: Avtomatlashtirish", "60 daqiqa: Dashboard", "30 daqiqa: Hujjat"],
          ["Takroriy ishni avtomatlashtirdim", "Dashboard qurdim", "Real vazifani hal qildim"],
          ["Hujjatsiz murakkab jadval", "Himoyasiz formulalar"],
          ["Dashboard", "Avtomatlashtirilgan hisobot", "Real loyiha"],
          ["Murakkablik", "Hujjat"], ["Dashboard", "Makros/Apps Script asoslari"]),
        S(4, "JOB READY", "Ishga tayyorlanish", 4, "3 soat", "Ariza va buyurtmalar",
          [("Portfolio yo'q", "Namuna jadvallar (shaxsiy ma'lumotsiz)"), ("Suhbatda test", "Vaqtli amaliy topshiriq mashqi")],
          ["60 daqiqa: Portfolio", "60 daqiqa: Ariza", "60 daqiqa: Test mashqi"],
          ["Namuna jadvallar tayyor", "Har hafta arizalar", "Amaliy testni bajara olaman"],
          ["Haqiqiy mijoz ma'lumotini ko'rsatish", "Rad javobidan keyin to'xtash"],
          ["Rezyume", "Namuna jadvallar", "Muntazam arizalar"],
          ["Raqobat", "Test topshiriq"], ["Suhbat", "Portfolio"]),
    ],
    [W(1, "Asoslar", ["Interfeys", "Ma'lumot kiritish", "Formatlash", "Saralash", "Filtr", "Birinchi jadval"]),
     W(2, "Formulalar", ["SUM va AVERAGE", "IF", "COUNTIF/SUMIF", "Matn formulalari", "Sana formulalari", "Mashq"]),
     W(3, "Qidiruv", ["Nisbiy/mutlaq havola", "XLOOKUP/VLOOKUP", "Ma'lumot tekshiruvi", "Takrorlarni topish", "Xato turlari", "Mashq"]),
     W(4, "Hisobot", ["Tozalash", "Pivot", "Grafik", "Shartli formatlash", "Dashboard eskizi", "Mini hisobot"])],
    ["Google Sheets'da bo'sh jadval ochish (bugun, 5 daqiqa)", "Bir haftalik xarajatlaringizni kiritish (bugun, 20 daqiqa)", "SUM va AVERAGE bilan jami va o'rtachani hisoblash (bugun, 20 daqiqa)"],
    MENTOR_GENERIC,
    [R("Microsoft — Excel help & learning", "https://support.microsoft.com/en-us/excel"), R("Google Sheets — Help", "https://support.google.com/docs"), R("Exceljet", "https://exceljet.net/")],
    [(1, "Birinchi jadval"), (5, "10 ta formula"), (10, "Pivot hisobot"), (16, "Dashboard va avtomatlashtirish"), (20, "Ariza va buyurtmalar")],
)
